### ISSUE TITLE
Eggs Spawning Chickens

### ISSUE THREAD

**Issue by Chicken9000** [GenDeathrow/Hatchery#1]
I think with this mod you should try and disabled the throwing aspect of minecraft eggs and your eggs to spawn a chicken.

**Comment by GenDeathrow** [comment]
I like to keep my mods highly customized so it could be an option in the config, but something like that would default to vanilla, only because in modpacks ppl may not use hatchery correctly. But I like the idea.. it makes sense.

**Comment by GenDeathrow** [comment]
Will be in next version... just check config file to change.

**Comment by GenDeathrow** [comment]
Its in the newest version
