### ISSUE TITLE
Mod Support for Improving Minecraft?

### ISSUE THREAD

**Issue by WenXin20** [GenDeathrow/Hatchery#10]
The [Improving MC Mod](https://minecraft.curseforge.com/projects/improving-minecraft) replaces the chicken with a wild chicken at first, would it be possible to support it?

**Comment by GenDeathrow** [comment]
Technically it should actually support it to a point. As long as they extend of vanilla chickens. But I will get the mod and do some test probably  after a couple more content dates.  Only thing I can see is if you put them in a nesting pen they will give you wild chicken eggs, manure and feathers.

**Comment by WenXin20** [comment]
Ok, I think the way they have it is so that after breeding wild chickens about 4 times, you'll get the vanilla chicken.

**Comment by Thiana** [comment]
Any progress on this? Breeding Wild Chickens gives a generic egg that cant be hatched. Thanks.

**Comment by GenDeathrow** [comment]
I will test this out over the week and see what its doing.

**Comment by WenXin20** [comment]
Thanks

**Comment by Exsolutus** [comment]
I'd just like to second this request. From the testing I have done, Hatchery does work to change the breeding behavior of Wild Chickens. However, the main feature of Wild Chickens eventually birthing vanilla chickens does not appear to carry over, as I've only gotten more Wild Chickens.

**Comment by GenDeathrow** [comment]
Sorry Ive had bug fixes and some features that had to be ready for sf3.. not thats calming down I have more time to look at these extras request
