### ISSUE TITLE
Roosters Spawn in Void biome

### ISSUE THREAD

**Issue by ArashiDragon** [GenDeathrow/Hatchery#100]
From my understanding of the [VOID biome ](http://minecraft.gamepedia.com/Biome#Neutral_and_other_biomes)

> A completely empty biome that generates only a single structure: a 33×33 stone platform with a single block of cobblestone in the center. **No mobs _(passive or hostile)_** can spawn without spawn eggs, monster spawners or commands. Can only be accessed through The Void superflat preset.

The Roosters spawn very heavily in the VOID biome (assuming because there're no other spawns.).

In the first 30 minutes of playing on the VOID map I was designing on, I have seen about 10 - 15 roosters.
In the same mod pack but on normal biomes, it playing for 3 hours I hadn't seen a single rooster.

Mod pack [SkyFactory 3](https://mods.curse.com/modpacks/minecraft/256183-ftb-presents-skyfactory-3) from the twitch/curse client. (with a few mods added for my own enjoyment).

**Comment by GenDeathrow** [comment]
There is not technically a void biome. It just means there is no world generation. I've seen a lot of sky factory 3 playthroughs and worked with the dev on sf3. And yes while you see roosters, but they are just pulled from a random chance from other animals. Now you could be in a biome they spawn in that no other animals spawn in. If you hit f3 and look at the biome it will tell you what biome your technically in.

**Comment by ArashiDragon** [comment]
it was something I was working on. Thought I explained more but must have been another mod that broke I explained it on.

I am trying to make a map similar to the original FTB pyramid MC 1.2.5 map. So I "set" the biome in a small area to "The Void" ID 127. And the roosters spawn like mad.

NO other mobs (hostile, neutral or passive) are allowed to spawn in The Void (per the description).
