### ISSUE TITLE
Chicken Spawning From Animal Nets....

### ISSUE THREAD

**Issue by JustinB77** [GenDeathrow/Hatchery#103]
So... i'm playing Sky Factory 3 and i'm starting to breed chickens. I ran into this problem as soon as I used an animal net on a chicken...
I place it in a patch of grass from the net and it does nothing. It wont accept seeds, it wont move... All I can do is push it.
If I spawn it in with an egg (NEI), it fine. It breeds, moves, everything, but as soon as I use a net on it and place it back down, I get the glitch again.
Please help, I would like to get some more chickens!
Thanks

**Comment by GenDeathrow** [comment]
Sounds like they lost thier ai. 
Did you ever place them into a nesting pen? 
Nesting pens seem to have a small glitch with losing their AI, 
but nets dont do that, they just pick the entity up.

**Comment by JustinB77** [comment]
Yea I've had them in a nesting pen but I tried it without the pen and they still lose the AI.

**Comment by JustinB77** [comment]
OK I just tried it and this time, only the net was fine, when I put them in a pen it messed up..
Last time the net was the main problem but for some reason not this time...

**Comment by GenDeathrow** [comment]
I wish I knew what was causing the pens to mess up.. as I haven't run into this issue before. I will be looking into whats causing it though.

**Comment by JustinB77** [comment]
Ok thanks, I'll keep an eye out for an update... is there any other file version that you know would work?

**Comment by GenDeathrow** [comment]
downgrading the the release version and not using the beta, but it will remove a lot of the new items. lagging will be worst when around nesting pens.

**Comment by JustinB77** [comment]
I tried that and it still wasn't working right... Ill try again and I'll tell you what happens

**Comment by JustinB77** [comment]
Same thing... downloaded the latest release (not beta/alpha) and the same thing happens...

**Comment by JustinB77** [comment]
I tried it with just those three mods (chickens, more, and hatchery) and it was fine... I dont know why in sky factory it glitches... maybe because they were glitched before the file change?
