### ISSUE TITLE
[Lagg] NestPenTileEntity

### ISSUE THREAD

**Issue by Whazaaaaa** [GenDeathrow/Hatchery#104]
Hello. My server has been lagging really badly because of your mod. I was wondering if there was something I can do in order to keep the mod but without the lagg

Here is a representation of /profile e from tickprofiler. It doesnt really have information other than that its the NestPenTileEntity that is lagging my server very badly.

```12.07 23:04:26 [Server] INFO TPS: 11.1
12.07 23:04:26 [Server] INFO Single Entity | Time/Tick |     %
12.07 23:04:26 [Server] INFO NestPenTileEntity {2287,74,12500}:0 |     1.730 | 2.581
12.07 23:04:26 [Server] INFO NestPenTileEntity {2282,72,12501}:0 |     1.582 | 2.361
12.07 23:04:26 [Server] INFO NestPenTileEntity {2282,74,12507}:0 |     1.520 | 2.267
12.07 23:04:26 [Server] INFO NestPenTileEntity {2282,74,12501}:0 |     1.519 | 2.266
12.07 23:04:26 [Server] INFO NestPenTileEntity {2282,74,12500}:0 |     1.519 | 2.266
12.07 23:04:26 [Server] INFO Chunk | Time/Tick |      %
12.07 23:04:26 [Server] INFO 0: 142, 781 |    54.269 | 80.964
12.07 23:04:26 [Server] INFO 0: 0, 0 |     3.649 |  5.444
12.07 23:04:26 [Server] INFO 0: -752, -79 |     2.409 |  3.594
12.07 23:04:26 [Server] INFO 0: -751, -79 |     1.094 |  1.632
12.07 23:04:26 [Server] INFO 0: 144, 784 |     0.859 |  1.281
12.07 23:04:26 [Server] INFO All Entities of Type | Time/Tick |      %
12.07 23:04:26 [Server] INFO NestPenTileEntity |    54.109 | 80.724
12.07 23:04:26 [Server] INFO tileentity.TileEntityPlug |     3.898 |  5.816
12.07 23:04:26 [Server] INFO item.EntityItem |     3.566 |  5.321
12.07 23:04:26 [Server] INFO TileEntityPoint |     0.731 |  1.090
12.07 23:04:26 [Server] INFO TileConduitBundle |     0.534 |  0.796
12.07 23:04:26 [Server] INFO Average Entity of Type | Time/tick | Calls
12.07 23:04:26 [Server] INFO NestPenTileEntity |     1.503 | 11988
12.07 23:04:26 [Server] INFO tile.TileAlfPortal |     0.068 |   328
12.07 23:04:26 [Server] INFO tile.TileQuantumDsu |     0.066 |   332
12.07 23:04:26 [Server] INFO tile.TileUse |     0.059 |  1664
12.07 23:04:26 [Server] INFO TileQuantumTank |     0.025 |   333```

Anything I can do against this immense lagg would be awesome.
Or if I have to provide some data for you to fix this in an upcoming version i'd love to do this.

**Comment by GenDeathrow** [comment]
what versions are you using? The only downside is that each nesting pen is a tile entity, if the server cant handle a lot of tile entities it will lag. Ive seen profiles where nesting pen wasn't the highest yet their was more than other tile entities. Ive worked on decreasing lag, but your best bet is to make sure if you using chunk loading that players dont chunk loads 100's of chickens pens when they aren't online.

**Comment by Whazaaaaa** [comment]
Running SkyFactory 3.0.13
with: hatchery-1.10.2-0.3.17
Guess there is not much to do besides going by bases with tons of nestpens then :(

**Comment by GenDeathrow** [comment]
I mean you would run into this issue with other tile entities in the number that nesting pens can get. Ive done my best to reduce lag caused, but Im getting to the point that their isn't much more I can do. Sorry I couldn't be more help.

**Comment by Whazaaaaa** [comment]
Hai @GenDeathrow one quick thing. This lagg only started after updating some of my modpacks. For example I updated SkyFactory3 from 3.0.10 to 3.0.13
Which updated hatchery from 0.3.11 to 0.3.17
So I think something happend between these versions that f'd something up with the nest pens.
Please take a look at this.

**Comment by GenDeathrow** [comment]
@Whazaaaaa I had a friend who runs servers take a look at this post. He says it looks like all those ticks are coming from the same location. He says someone maybe bogging the server down cause he is got some kinda of crazy system.  He says a screen shot of that area may help.
