### ISSUE TITLE
[WIP problems] feather shredder

### ISSUE THREAD

**Issue by macks2008** [GenDeathrow/Hatchery#107]
So I started playing around with your work-in-progress items and, as is to be expected with work in progress stuff, I'm encountering some problems. First and foremost, the feather shredder's interface is as buggy as heck. Feathers placed into the input slot cannot be removed and will be destroyed if the block is broken. The RF meter doesn't seem to stay charged, but I can't tell if it's destroying energy or just not displaying it correctly.

If I find anything else wrong with the shredder, I'll be sure to add it here. If I find something wrong with other machines, I'll make a separate issue

**Comment by GenDeathrow** [comment]
I have a fix for the RF, its just a display issue. Yeah I have to work on the shredder interface, I think I may have fixed the issue with not being able to remove feathers too. I just don't have an update pushed just yet.

**Comment by GenDeathrow** [comment]
Should be fixed in latest version 0.3.19
