### ISSUE TITLE
[Bug] Chicken disappears after inserting in pen containing a chicken

### ISSUE THREAD

**Issue by KikiGerritsen** [GenDeathrow/Hatchery#109]
So, I've had this problem several times while I was cross breeding chicken. To cross breed I made a setup of two pens next to each other. After I inserted a (e.g.) sand chicken, I wanted to put the water chicken next to it. But I accidentally clicked the pen where the sand chicken was in. After doing that, my water chicken disappeared and I had to remake my water chicken.

**Comment by H1nk** [comment]
+1 Experiencing the same exact issue in Sky Factory 3.

**Comment by GenDeathrow** [comment]
heck I cant even test this atm.. I'll have to get my system fixed here. before I can do this. I'll get back to ya about this.

**Comment by GenDeathrow** [comment]
should be fixed.. latest version 0.3.19
