### ISSUE TITLE
FTB Beyond Crash

### ISSUE THREAD

**Issue by Ian-Luminus** [GenDeathrow/Hatchery#110]
Added Hatchery after I had gen'd some of the world (to the point of killing the dragon) and started getting this crash after trying to generate new land, even in the End.

`java.lang.IllegalArgumentException`
`	at net.minecraft.util.WeightedRandom.func_76273_a(SourceFile:18)`
`	at net.minecraft.util.WeightedRandom.func_76271_a(SourceFile:37)`
`	at net.minecraft.world.WorldServer.func_175734_a(WorldServer.java:241)`
`	at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:126)`
`	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:198)`
`	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)`
`	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)`
`	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)`
`	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)`
`	at java.lang.Thread.run(Unknown Source)`

`-- Head --`
`Thread: Server thread`
`Stacktrace:`
`	at net.minecraft.util.WeightedRandom.func_76273_a(SourceFile:18)`
`	at net.minecraft.util.WeightedRandom.func_76271_a(SourceFile:37)`
`	at net.minecraft.world.WorldServer.func_175734_a(WorldServer.java:241)`
`	at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:126)`
`	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:198)`

Further debugged by removing Hatchery and going to the same areas, no server crash. Can also prevent the crash by booting server, doing `/gamerule doMobSpawning false` then moving to a known safe area and setting it back to true. I'm hoping that fix will help you narrow down the issue. Also mentioned this as Beyond because I built off that pack so you know which other mods there are.

**Comment by GenDeathrow** [comment]
Did you happen to make the new Lucky egg machine?

**Comment by Ian-Luminus** [comment]
No, I did not. As I mentioned, the doMobSpawning gamerule being disabled prevented the crash.

Looking back at the log file, this is with the 0.3.11 version. But I was unable to find any information related to this anywhere, so it's possibly still relevant. I'll try the latest version tomorrow.

**Comment by GenDeathrow** [comment]
Unfortunately that crash isn't specific at all, its not your fault. My guess is the ModPack may be messing with mob spawns with another mod, and its interfering with hatchery. I cant say this is a mod issue, because it could be a pack issue. I would need other reports to really narrow it down.

**Comment by GenDeathrow** [comment]
Is the Rooster config spawn weight/percentage set to 0?

**Comment by GenDeathrow** [comment]
https://github.com/GenDeathrow/Hatchery/issues/115

**Comment by Ian-Luminus** [comment]
It was, yes. Wasn't aware that disabling them would cause this, I just wanted to save a little on system resources. Maybe some kind of check for the config file that sees the weight chance as 0 and just disables the entire rooster spawning system instead of having to add a new config option and/or throw errors when its set to 0?

**Comment by GenDeathrow** [comment]
I'll set it up to not do 0, but using a mod like https://minecraft.curseforge.com/projects/in-control gives you complete control over entity spawning.
