### ISSUE TITLE
[Request] Egg neutralization

### ISSUE THREAD

**Issue by charlesbevans** [GenDeathrow/Hatchery#114]
I'd like a way to convert ChickensMod eggs back to vanilla for storing the excess. (Especially when you have stacks of 1 or 2 log chicken eggs in various stages of evolution.) Once you have a 10/10/10 of every chicken and extras of ones you need more of voiding becomes necessary. I can turn them into food with Cook the Eggs!, but I've got to do it one or two eggs at a time because of the metadata. Plus, Cooking for Blockheads doesn't seem to recognize them as eggs.

**Comment by birb-ebooks** [comment]
I second this. I've usually just set up a system to void everything but that can take forever to get right, especially with all the metadata.

**Comment by GenDeathrow** [comment]
this has been requested a few times.. will be in next update.

**Comment by GenDeathrow** [comment]
Done
