### ISSUE TITLE
[Bug] Chicken Deletion on Full Pen

### ISSUE THREAD

**Issue by ReltivlyObjectv** [GenDeathrow/Hatchery#118]
**Replication**:
Using an animal net, if you try to place a chicken in a nesting pen that is already occupied, the chicken in your net is removed from the net, but not placed in the world. This effectively just deletes whatever chicken is in your net.

**Environment**:
I encountered this bug while playing the current version of Sky Factory 3 (3.0.14) on a server run on Linux (Ubuntu) and a client ran on OS X (10.12.6).

**Comment by IamAlathe** [comment]
I lost a couple of chickens this way in my Sky Factory also.  I just thought maybe they glitched and went over the edge or something at first.  But then I had it happen and I wasn't near an edge.

**Comment by GenDeathrow** [comment]
I believe this was already fixed. Either update to skyfactory 3 (3.0.15) or update hatchery to latest.

https://minecraft.curseforge.com/projects/hatchery/files/2481130.. but even this version has a few quirks to it.. Im working on fixing them.
