### ISSUE TITLE
Chickens & Item Spawns Going To Void?

### ISSUE THREAD

**Issue by Muzixs** [GenDeathrow/Hatchery#119]
Super weird. Here's a [clip ](https://www.dropbox.com/s/byucckb1xajrwq0/2017-10-16%2020-10-57.mp4?dl=0)detailing an overview of the issue. Please note we had this issue before on a vanilla none Sponge server with no plugins. 

**Problem:** Chicken noises and items spawning at coordinates 0,0,0.

**Steps to reproduce:** No idea.

**Comment by GenDeathrow** [comment]
Sponge server?

**Comment by Muzixs** [comment]
This one, yes. 

Sponge: 1.10.2-2477-5.2.0-BETA-2691

Forge: 12.18.3.2511

**Comment by GenDeathrow** [comment]
its a Sponge issue, They aren't properly handling a forge method, and has been in their issue for months. They haven't responded in a long time and I don't think they are going to fix it. But this is the only way I can handle it.
