### ISSUE TITLE
Server Crash at capability.AnimalStats

### ISSUE THREAD

**Issue by rckymtnrfc** [GenDeathrow/Hatchery#12]
Just updated to 0.1.7 and I got the following crash on the server about 2 mins after logging in.

http://pastebin.com/MsAuKy1Q

Thanks for looking into this.

**Comment by GenDeathrow** [comment]
Oh crap.. that was just stupid on my part.. forgot that is a clientside call. Well this mod is in beta for a good reason.. I didn't even think to test that. will have a fix in next couple of hours. Thanks for telling me

**Comment by GenDeathrow** [comment]
To be honest.. the crash was from something that was suppose to be removed before I had posted the file. But I must have missed it for removal

**Comment by GenDeathrow** [comment]
Fixed
