### ISSUE TITLE
Animal Net/Nesting Pen Compatability

### ISSUE THREAD

**Issue by marvelfandomonium** [GenDeathrow/Hatchery#121]
(version 10.2.1 via Twitch/Skyfactory 3) When I've collected a chicken in the net, and then right-click on the nesting pen, it opens the inventory on the nesting pen and doesn't place the chicken in the pen. am I missing a step or am I using the incorrect key or is it something else?

**Comment by IamAlathe** [comment]
Try shift-clicking.  Right-click is the default to open the inventory, shift-right click should allow you to place the chicken.

**Comment by marvelfandomonium** [comment]
Thanks, I'll try that. I thought of that after I left for work, so I'll find out when I get home. Thanks again for the suggestion.

**Comment by marvelfandomonium** [comment]
@IamAlathe yep, that works like a charm! Thanks.
