### ISSUE TITLE
Game stuck on "Building terrain" after adding the mod to my pack. (1.11.2)

### ISSUE THREAD

**Issue by Wizardon777** [GenDeathrow/Hatchery#122]
**Issue Description:**

My 1.11.2 mod pack (Sky Arsenal) won't load the world after adding the "Hatchery" mod.
No crash, just stuck for over 45 minutes.
The pack memory usage shot up to over 12GB.

Happens with old and newly created worlds.

(After removing the mod, the pack is working fine.)

**Steps to reproduce (important):**

There's a lot of mods in this pack (about 200), so perhaps it's an inter-mod thing.
The list of mods can be found here: [Link to Sky Arsenal page](https://minecraft.curseforge.com/projects/sky-arsenal)

Just added the mod to pack, replaced "Roost" mod with it.
Removed "ToManyChickens" mod and replaced with "Chickens" and "MoreChikens" mods

**What happens:**

Game stuck on "Building terrain".

**What you expected to happen:**

World to load.

**Affected Versions (Do not use "latest"):**

Chickens: chickens-5.0.1
Minecraft: 1.11.2
Forge: 13.20.0.2530

**Comment by GenDeathrow** [comment]
Strange Hatchery doesn't add any kind of terrain gen stuff, I'l play around with it and see whats happening. Is there any kinda of logs?

**Comment by GenDeathrow** [comment]
I sort of checked this before i had to rush to work. From my log i had a crap ton of errors.. nothing pointng directly to hatchery. But i didnt have enough time to look at it. So if you can get me a log, ill try to go over this when i get free time. Other than that it will be later today

**Comment by GenDeathrow** [comment]
Ok, so I had to remove a couple of mods to figure out whats going on. It seems like it has something to do with possible minetweaker and  recipes maybe.. first I thought journamap was the issue. removed that, than cooking for block heads showed up... removed that. and immersive engineering/minetweaker is showing errors. they all seem to deal with recipe checking.. I guess with food. looking into it more later

**Comment by Wizardon777** [comment]
While checking it myself I did not get any errors, just a freeze (no log).
I'm looking into it myself, perhaps something is clashing elsewhere.
Updated all mods to latest version just in case, removed an old line in minetweaker that deals with "ToManyChickens" mod, still freeze.

**Comment by GenDeathrow** [comment]
@Wizardon777 I got it figured out.. I'll have a fix tonight. its all the recipe changes apparently... my old custom handlers don't work as intended anymore.. so I have to remove them or fix them some how.  I had an idea what it was, but didn't realize it cause this much issue.

**Comment by Wizardon777** [comment]
Oh! Thank you very much!
Keep up the good work!

**Comment by GenDeathrow** [comment]
Ill reopen if its still an issue.. but I was able to start the world up in my testing
