### ISSUE TITLE
Some chickens in nesting pens are black (1.11.2)

### ISSUE THREAD

**Issue by Wizardon777** [GenDeathrow/Hatchery#123]
Don't know the reason, but found some chickens to be black in nesting pen (broken texture perhaps?).

**Example:**
![2017-11-18_15 27 37](https://user-images.githubusercontent.com/22551232/32980776-9b591390-cc75-11e7-8c5b-b1424d9edbec.png)

**Comment by GenDeathrow** [comment]
its probably a lighting issue when rendering the model. I make sure the block isn't messing with the lighting at all.

**Comment by Wizardon777** [comment]
I thought so too, but when I switched them around the gold chicken was visible  in the place of the emerald one, and the emerald one was still black in the left nesting pen.

**Comment by GenDeathrow** [comment]
Thats super strange than. No idea. Ill still play around with it.

**Comment by Wizardon777** [comment]
Found out it was another mod interfering with lighting, no further investigation needed, Thank you!

**Comment by GenDeathrow** [comment]
Thanks.. what mod was it?
