### ISSUE TITLE
Changing Worlds - stuck in loop

### ISSUE THREAD

**Issue by Immaculala** [GenDeathrow/Hatchery#124]
Hatchery-1.11.2-1.0.2 Beta - Single Player
I get stuck in never-ending loop when changing worlds.
Only way to get out the loop is with ‘End Task’.
I saw in your notes you’re already aware of this, just letting you know it’s not fixed yet.
Keep up the good work :)

**Comment by GenDeathrow** [comment]
It was Fixed in version 1.0.3

**Comment by Immaculala** [comment]
Doh! I'm an idiot :(
Sorry :P
