### ISSUE TITLE
1.10 Server ticks?

### ISSUE THREAD

**Issue by tyler489** [GenDeathrow/Hatchery#127]
I recently opened a skyfactory 3 server it has an average of 30 players on and i noticed that the chickens mod and hatchery mods are consuming around 1/4 the server tick time each.  https://timings.aikar.co/?id=c0436b2bef1d44389bbae76f55076c03 is there any way to cut this back a bit i just nuked all the chickens in the world removing just over 200 and would hate to have to disable hatchery and chickens.

**Comment by GenDeathrow** [comment]
Hatchery already reduces ticks as much as I can(I remove the entities AI and movement). But they are still tile entities and use up ticks. If your users are chunk loading tons of chickens that's going to happen with any tick-able tile entity.  All I can say is tell them to reduce their nesting pens. a 10-10-10 chicken produces items quickly.

Also it appears your using sponge forge.. I would say remove sponge for as they wont fix incompatibilities with forge specific methods, that I and a couple other modders use. Which have caused some tick lag, excess entities around 0,0,0. Items not getting caught in nesting pens. multitude of other issues.

**Comment by tyler489** [comment]
Yeah not really an option As the only other thing to do is use FTB claims for Protection and thats Broken to.
But 20 Hatchery nests with only 8 chickens in them is able to bring the server down to 1 TPS... From 20

**Comment by GenDeathrow** [comment]
Well its strange your getting that, but I know of servers who have not had this issue, and are using a lot more nesting pens than that. I mean a heck of a lot more. Have you tried using a none sponge forge server? Like I said Sponge has had way too many issues with mods. For example do you have pre-merge items turned "off" or "on" in sponge?

**Comment by tyler489** [comment]
not sure why that closed. Ill look at that
