### ISSUE TITLE
Server crash on load with error (1.11.2)

### ISSUE THREAD

**Issue by Wizardon777** [GenDeathrow/Hatchery#128]
**Issue Description:**
Server crash on start.

**Steps to reproduce (important):**
Use mod on server.

**What happens:**

Server crash on load with error:
Caught exception from hatchery (java.lang.NoClassDefFoundError: net/minecraft/client/renderer/color/IItemColor)

**Affected Versions):**

Hatchery: hatchery-1.11.2-1.0.3
Minecraft: 1.11.2
Forge: 13.20.0.2530

Crash report:
[crash-2017-11-25_15.52.40-server.txt](https://github.com/GenDeathrow/Hatchery/files/1503121/crash-2017-11-25_15.52.40-server.txt)

**Comment by Wizardon777** [comment]
**oops, wrong crash log!**

[crash-2017-11-25_16.11.31-server.txt](https://github.com/GenDeathrow/Hatchery/files/1503197/crash-2017-11-25_16.11.31-server.txt)

**Comment by GenDeathrow** [comment]
Working on it.. Sorry servers haven't been tested yet, I was still trying to fix all the client crashes.. and I forgot to test server this last run.

**Comment by Wizardon777** [comment]
No problem, I know it's a hard work, if you'd like I think I can help with coding and testing.

Keep up the good work!

**Comment by GenDeathrow** [comment]
sorry back from all my vacation stuff. and over a sickness that dropped me for extra days. I believe I just pushed an update that should fix that issue. Sorry it took so long to get it out.
