### ISSUE TITLE
1.10.2 Hatchery -- Nesting Pens Hurting Chickens?

### ISSUE THREAD

**Issue by AlmightyHail** [GenDeathrow/Hatchery#129]
I kept checking on my chickens that're in their nesting pens and finding them losing half-hearts, lit up in red in their pens. This only happens on this one map for some reason. When I checked the area, nothing could be hurting them.

**Comment by GenDeathrow** [comment]
what version are you on?

**Comment by GenDeathrow** [comment]
what version of the mod?

**Comment by AlmightyHail** [comment]
Oh sorry, I should've specified. 
The Hatchery file is "hatchery-1.10.2-0.2.10"
It's affecting the chickens in my multiplayer server too, now, which has the same version.

**Comment by GenDeathrow** [comment]
Your on a very old version. 1.10 hatchery is currently on version 0.3.22 . Which fixed should have contained a fix for that. Your about 12 versions behind.
