### ISSUE TITLE
Items dissapearing

### ISSUE THREAD

**Issue by NightmareElmo** [GenDeathrow/Hatchery#13]
When right clicking a nesting pen with any item they disappear from my inventory, and only reappear when another inventory is opened. If the item is placeable, it places for a split second then disappears, but will still reappear when another inventory is opened.

**Comment by GenDeathrow** [comment]
Little confused on this one. Are you talk I about an item in your hand disappearing? Anyways thats a client server desync. ill check it, but havent seen that happen yet.

**Comment by NightmareElmo** [comment]
yes it leaves my hand and my inventory, its like im using the item, but im not because it re-appears after I access another inventory

**Comment by GenDeathrow** [comment]
I Saw this happen the other day. not sure whats causing it. but it now needs more research
