### ISSUE TITLE
Only roosters ever spawn

### ISSUE THREAD

**Issue by Deuxis** [GenDeathrow/Hatchery#130]
version: 0.3.22 (MC 1.10.2, Forge 1.10.2-12.18.3.2488)
As the title says, the only chickens to ever spawn are rooster groups. (1-2 with default config) Also, please provide a config option to just disable roosters. Even with spawn chance and min/max group sizes set to 0 I've *still* encountered occasional roosters (with normal generation), even if it seemed to enable other chickens to spawn.

Steps to reproduce:
1. Load up Minecraft 1.10.2 with Hatchery 0.3.22
2. Generate a world, fly around
3. Watch as roosters are literally the only chicken type that is spawning
4. ???
5. Profit!

**Comment by GenDeathrow** [comment]
I think something else is messing with your pack. I just started up 4 worlds flew 4000 blocks, found 1 rooster, and found 30 chickens.  I cant recreate this. Only mods I have installed are chickens/more chickens/ waila/ TOP/ JEI installed. Also SF3 uses this, and I work closely with the Dev. I haven't heard of this one yet. 

 You also cant set group size to 0 as it will default to 1. Crashes happen with 0. 

 If you want to disable you can use mods like [InControl](https://minecraft.curseforge.com/projects/in-control?gameCategorySlug=mc-mods&projectID=257356) to disable mobs.  I haven't made changes to 1.10 in a long while. currently working on 1.11 and 1.12 ports.  So I will prolly not get to this. I can't say ever, but not atm. 

If you figure it out, or have any new information on the issue I be glad to fix it. but atm, I cant figure this one out.
