### ISSUE TITLE
[1.11.2] Animal net dup bug

### ISSUE THREAD

**Issue by vintagetechfan** [GenDeathrow/Hatchery#131]
Can duplicate animal nets if I have 2 or more stacked in my hot bar and pick up an animal with one, the net with the animal moves to an empty space but I continue to have the same number in my hot bar.

Running Minecraft SMP 1.11.2 with Hatchery 1.1.0.

**Comment by GenDeathrow** [comment]
welp.. good catch. not sure how I missed that. Man thats bug has been out for a while now. It happens becauses I added in stack able nets. At least this dupe bug isn't a bad one. nets are easy to make.

**Comment by GenDeathrow** [comment]
https://github.com/GenDeathrow/Hatchery/commit/051427acac1fe093eafb16bb9d99fbf89639d7a8
