### ISSUE TITLE
Fertilizer Mixer, Methane Digester, Lucky Egg Machine do not have GUIs

### ISSUE THREAD

**Issue by IamAlathe** [GenDeathrow/Hatchery#133]
I created each of these machines in turn and cannot access them.  I've tried right clicking, left clicking, shift right and left clicking, and smacking them or right clicking them with ingredients intended to be used in them.  There also appears to be no WAILA/WAWLA type support for the Lucky Egg Machine.  Lucky Egg Machine did however absorb power from a generator when I put it next to it.

The only Hatchery/Chickens settings I've altered are to make breeding give babies instead of eggs, and showing stats in WAILA without needing to analyze.  (Eggs do not show stats, only type, not sure if that's intended in this version)

Minecraft Version:  1.12.2
Forge Version:  14.23.1.2582
Hatchery Version:  1.12.2-2.0.0

**Comment by GenDeathrow** [comment]
Should be Fixed in 2.0.2 already. I released it last night

**Comment by IamAlathe** [comment]
Sweet!  Thank you.  I've never used TOP before, maybe I'll give it a shot.
