### ISSUE TITLE
Eggs do not convert/are not usable

### ISSUE THREAD

**Issue by IamAlathe** [GenDeathrow/Hatchery#134]
According to JEI, I should be able to put a Hatchery egg in a crafting table and get vanilla eggs.  This does not work.  Nor can they be used as eggs in Pam's Harvestcraft, which JEI also shows should be an option.  These are eggs laid by Chickens chickens, taken from pens, mostly.  They are not a generic Hatchery egg, but say a bone white chicken egg or coal chicken egg.  Requesting uses for them shows that Hatchery eggs can be converted, or used directly with Pam's recipes.  I'm guessing this is a bug?

Minecraft Version: 1.12.2
Forge Version: 14.23.1.2582
Hatchery Version: 1.12.2-2.0.0

**Comment by GenDeathrow** [comment]
I'll look into it, something may have changed in this version particularly

**Comment by GenDeathrow** [comment]
Well it appears to be an issue with nbt data in the new recipe system... atm Im not sure how to fix this. I could possibly fix this in a much later update. but not the next update.

**Comment by IamAlathe** [comment]
That sounds like a pain.  At least we have a use for them in the meantime.  Lots of Lucky Eggs! :)

**Comment by Syndaryl** [comment]
I'll gist my CT script when I get home and post it here in case other people find it useful until you find a solution.
