### ISSUE TITLE
Chicken Feeder causes server crashes.

### ISSUE THREAD

**Issue by legracen** [GenDeathrow/Hatchery#135]
Both When placed ontop of a hopper (done by accident) and when being stored in a Storage Drawers mod Drawer:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-0.12-75-core.jar)
  OTGCorePlugin (OTG-Core.jar)
  IELoadingPlugin (ImmersiveEngineering-0.12-76-core.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.3.9.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.3.0.jar)
  CoreMod (Aroma1997Core-1.12.2-1.3.0.2.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.4.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.5.jar)
  TransformerLoader (OpenComputers-MC1.12.1-1.7.1.43.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  MDECore-Core (mdecore-1.12-1.0.jar)
Contact their authors BEFORE contacting forge

// Sorry :(

Time: 1/3/18 11:47 AM
Description: Exception ticking world

java.lang.ClassCastException: com.jaquadro.minecraft.storagedrawers.block.tile.TileEntityDrawersStandard$Slot1 cannot be cast to com.gendeathrow.hatchery.block.feeder.FeederTileEntity
        at com.gendeathrow.hatchery.block.feeder.FeederBlock.func_180650_b(FeederBlock.java:74)
        at net.minecraft.block.Block.func_180645_a(Block.java:508)
        at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:475)
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:225)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
        at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
        at com.gendeathrow.hatchery.block.feeder.FeederBlock.func_180650_b(FeederBlock.java:74)
        at net.minecraft.block.Block.func_180645_a(Block.java:508)
        at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:475)
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:225)

-- Affected level --
Details:
        Level name: CPM
        All players: 0 total; []
        Chunk stats: ServerChunkCache: 809 Drop: 0
        Level seed: 2075315
        Level generator: ID 07 - OTG, ver 0. Features enabled: true
        Level generator options: OpenTerrainGenerator
        Level spawn location: World: (256,63,244), Chunk: (at 0,3,4 in 16,15; contains blocks 256,0,240 to 271,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
        Level time: 10715716 game time, 4061266 day time
        Level dimension: 0
        Level storage version: 0x04ABD - Anvil
        Level weather: Rain time: 126584 (now: false), thunder time: 82076 (now: false)
        Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
        at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
        Minecraft Version: 1.12.2
        Operating System: Linux (amd64) version 4.9.68-x86_64-linode89
        Java Version: 1.8.0_151, Oracle Corporation
        Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
        Memory: 2019771712 bytes (1926 MB) / 6133186560 bytes (5849 MB) up to 6407585792 bytes (6110 MB)
        JVM Flags: 6 total; -Xmx6g -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:ParallelGCThreads=4 -XX:+AggressiveOpts
        IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
        FML: MCP 9.42 Powered by Forge 14.23.1.2575 108 mods loaded, 107 mods active
        States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

        | State     | ID                   | Version                  | Source                                             | Signature                                |
        |:--------- |:-------------------- |:------------------------ |:-------------------------------------------------- |:---------------------------------------- |
        | UCHIJAAAA | minecraft            | 1.12.2                   | minecraft.jar                                      | None                                     |
        | UCHIJAAAA | mcp                  | 9.42                     | minecraft.jar                                      | None                                     |
        | UCHIJAAAA | FML                  | 8.0.99.99                | forge-1.12.2-14.23.1.2575-universal.jar            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
        | UCHIJAAAA | forge                | 14.23.1.2575             | forge-1.12.2-14.23.1.2575-universal.jar            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
        | UCHIJAAAA | ivtoolkit            | 1.3.3-1.12               | minecraft.jar                                      | None                                     |
        | UCHIJAAAA | otgcore              | 1.12                     | minecraft.jar                                      | None                                     |
        | UCHIJAAAA | openmodscore         | 0.11.4                   | minecraft.jar                                      | None                                     |
        | UCHIJAAAA | opencomputers|core   | 1.7.1.43                 | minecraft.jar                                      | None                                     |
        | UCHIJAAAA | actuallyadditions    | 1.12.2-r126              | ActuallyAdditions-1.12.2-r126.jar                  | None                                     |
        | UCHIJAAAA | appliedenergistics2  | rv5-stable-4             | appliedenergistics2-rv5-stable-4.jar               | None                                     |
        | UCHIJAAAA | bdlib                | 1.14.3.10                | bdlib-1.14.3.10-mc1.12.2.jar                       | None                                     |
        | UCHIJAAAA | ae2stuff             | 0.7.0.4                  | ae2stuff-0.7.0.4-mc1.12.2.jar                      | None                                     |
        | UCHIJAAAA | crafttweaker         | 4.0.12                   | CraftTweaker2-1.12-4.0.12.jar                      | None                                     |
        | UCHIJAAAA | mtlib                | @VERSION@                | MTLib-3.0.1.jar                                    | None                                     |
        | UCHIJAAAA | modtweaker           | 4.0.6                    | modtweaker-4.0.6.jar                               | None                                     |
        | UCHIJAAAA | jei                  | 4.8.5.138                | jei_1.12.2-4.8.5.138.jar                           | None                                     |
        | UCHIJAAAA | appleskin            | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                         | None                                     |
        | UCHIJAAAA | aroma1997core        | 1.3.0.2                  | Aroma1997Core-1.12.2-1.3.0.2.jar                   | dfbfe4c473253d8c5652417689848f650b2cbe32 |
        | UCHIJAAAA | aroma1997sdimension  | 1.3.0.0.b37              | Aroma1997s-Dimensional-World-1.12-1.3.0.0.b37.jar  | None                                     |
        | UCHIJAAAA | mdecore              | 1.12-1.0                 | mdecore-1.12-1.0.jar                               | None                                     |
        | UCHIJAAAA | autooredictconv      | 1.12-1.0                 | autooredictconv-1.12-1.0.jar                       | None                                     |
        | UCHIJAAAA | baubles              | 1.5.1                    | Baubles-1.12-1.5.1.jar                             | None                                     |
        | UCHIJAAAA | bibliocraft          | 2.4.3                    | BiblioCraft[v2.4.3][MC1.12.0].jar                  | None                                     |
        | UCHIJAAAA | bookshelf            | 2.3.518                  | Bookshelf-1.12.2-2.3.518.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
        | UCHIJAAAA | botania              | r1.10-352                | Botania r1.10-352.jar                              | None                                     |
        | UCHIJAAAA | codechickenlib       | 3.1.5.331                | CodeChickenLib-1.12.2-3.1.5.331-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
        | UCHIJAAAA | redstoneflux         | 2.0.1                    | RedstoneFlux-1.12-2.0.1.2-universal.jar            | d4f1503fbacd9b9fb767720420c5395104239ec9 |
        | UCHIJAAAA | brandonscore         | 2.3.7                    | BrandonsCore-1.12-2.3.7.140-universal.jar          | None                                     |
        | UCHIJAAAA | chameleon            | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                           | None                                     |
        | UCHIJAAAA | chesttransporter     | 2.8.7                    | ChestTransporter-1.12-2.8.7.jar                    | None                                     |
        | UCHIJAAAA | chickens             | 6.0.2                    | chickens-6.0.2.jar                                 | None                                     |
        | UCHIJAAAA | chisel               | MC1.12-0.1.1.24          | Chisel-MC1.12-0.1.1.24.jar                         | None                                     |
        | UCHIJAAAA | chiselsandbits       | 14.11                    | chiselsandbits-14.11.jar                           | None                                     |
        | UCHIJAAAA | cofhcore             | 4.3.8                    | CoFHCore-1.12.2-4.3.8.29-universal.jar             | None                                     |
        | UCHIJAAAA | cofhworld            | 1.1.1                    | CoFHWorld-1.12.2-1.1.1.12-universal.jar            | None                                     |
        | UCHIJAAAA | cookingforblockheads | 6.3.17                   | CookingForBlockheads_1.12.1-6.3.17.jar             | None                                     |
        | UCHIJAAAA | coralreef            | 2.0                      | CoralReef-2.2-1.12.2.jar                           | None                                     |
        | UCHIJAAAA | craftingtweaks       | 8.1.6                    | CraftingTweaks_1.12.1-8.1.6.jar                    | None                                     |
        | UCHIJAAAA | crafttweakerjei      | 2.0.0                    | CraftTweaker2-1.12-4.0.12.jar                      | None                                     |
        | UCHIJAAAA | waila                | 1.8.23                   | Hwyla-1.8.23-B38_1.12.jar                          | None                                     |
        | UCHIJAAAA | mantle               | 1.12-1.3.1.21            | Mantle-1.12-1.3.1.21.jar                           | None                                     |
        | UCHIJAAAA | tconstruct           | 1.12-2.8.1.49            | TConstruct-1.12-2.8.1.49.jar                       | None                                     |
        | UCHIJAAAA | p455w0rdslib         | 2.0.24                   | p455w0rdslib-1.12-2.0.24.jar                       | None                                     |
        | UCHIJAAAA | danknull             | 1.3.29                   | DankNull-1.12-1.3.29.jar                           | None                                     |
        | UCHIJAAAA | darkutils            | 1.7.181                  | DarkUtils-1.12.2-1.7.181.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
        | UCHIJAAAA | thermalfoundation    | 2.3.8                    | ThermalFoundation-1.12.2-2.3.8.22-universal.jar    | None                                     |
        | UCHIJAAAA | draconicevolution    | 2.3.7                    | Draconic-Evolution-1.12-2.3.7.278-universal.jar    | None                                     |
        | UCHIJAAAA | dynmap               | 2.6-beta-1-3             | Dynmap-2.6-beta-1-forge-1.12.jar                   | None                                     |
        | UCHIJAAAA | embers               | 0.230                    | embers-0.230.jar                                   | None                                     |
        | UCHIJAAAA | enderstorage         | 2.4.2.126                | EnderStorage-1.12.2-2.4.2.126-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
        | UCHIJAAAA | ftbl                 | 4.2.5                    | FTBLib-4.2.5.jar                                   | None                                     |
        | UCHIJAAAA | shetiphiancore       | 3.5.5                    | shetiphiancore-1.12.0-3.5.5.jar                    | None                                     |
        | UCHIJAAAA | endertanks           | 1.6.3                    | endertanks-1.12.0-1.6.3.jar                        | None                                     |
        | UCHIJAAAA | exnihilocreatio      | 1.12-0.1.5               | exnihilocreatio-1.12-0.1.5.jar                     | None                                     |
        | UCHIJAAAA | extracells           | 2.5.10                   | ExtraCells-1.12.2-2.5.10a47.jar                    | None                                     |
        | UCHIJAAAA | extrautils2          | 1.0                      | extrautils2-1.12-1.7.2.jar                         | None                                     |
        | UCHIJAAAA | natura               | 1.12-4.3.0.23            | natura-1.12-4.3.0.23.jar                           | None                                     |
        | UCHIJAAAA | forestry             | 5.7.0.219                | forestry_1.12.2-5.7.0.219.jar                      | None                                     |
        | UCHIJAAAA | farmingforblockheads | 3.1.5                    | FarmingForBlockheads_1.12-3.1.5.jar                | None                                     |
        | UCHIJAAAA | foamflower           | 1.12.2-1.0.0.0-beta1     | foamflower-1.12.2-1.0.0.0-beta1.jar                | None                                     |
        | UCHIJAAAA | ftbu                 | 4.2.4                    | FTBUtilities-4.2.4.jar                             | None                                     |
        | UCHIJAAAA | gendustry            | 1.6.5.6                  | gendustry-1.6.5.6-mc1.12.2.jar                     | None                                     |
        | UCHIJAAAA | advgenerators        | 0.9.20.9                 | generators-0.9.20.9-mc1.12.2.jar                   | None                                     |
        | UCHIJAAAA | hatchery             | 2.0.2                    | hatchery-1.12.2-2.0.2.jar                          | None                                     |
        | UCHIJAAAA | immersiveengineering | 0.12-76                  | ImmersiveEngineering-0.12-76.jar                   | 4cb49fcde3b43048c9889e0a3d083225da926334 |
        | UCHIJAAAA | storagedrawers       | 1.12-5.2.5               | StorageDrawers-1.12.1-5.3.3.jar                    | None                                     |
        | UCHIJAAAA | refinedstorage       | 1.5.31                   | refinedstorage-1.5.31.jar                          | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
        | UCHIJAAAA | immersivecables      | 1.2.0.1                  | ImmersiveCables-1.12.2-1.2.0.1.jar                 | None                                     |
        | UCHIJAAAA | immersivepetroleum   | @VERSION@                | immersivepetroleum-1.12.2-1.1.6.jar                | None                                     |
        | UCHIJAAAA | immersivetech        | 1.3.4                    | immersivetech-1.12-1.3.4.jar                       | None                                     |
        | UCHIJAAAA | inventorytweaks      | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                           | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
        | UCHIJAAAA | ironbackpacks        | 1.12.2-3.0.2-3           | IronBackpacks-1.12.2-3.0.2-3.jar                   | None                                     |
        | UCHIJAAAA | ironchest            | 1.12.2-7.0.34.820        | ironchest-1.12.2-7.0.34.820.jar                    | None                                     |
        | UCHIJAAAA | japta                | 1.11.15                  | JAPTA-1.12-1.11.15.jar                             | None                                     |
        | UCHIJAAAA | jeibees              | 0.9.0.5                  | jeibees-0.9.0.5-mc1.12.2.jar                       | None                                     |
        | UCHIJAAAA | jepb                 | 1.2.1                    | jepb-1.12-1.2.1.jar                                | None                                     |
        | UCHIJAAAA | journeymap           | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                        | None                                     |
        | UCHIJAAAA | lunatriuscore        | 1.2.0.42                 | LunatriusCore-1.12.2-1.2.0.42-universal.jar        | None                                     |
        | UCHIJAAAA | magicbees            | 1.0                      | MagicBees-1.12-3.1.7.jar                           | None                                     |
        | UCHIJAAAA | malisiscore          | 1.12.2-6.3.0             | malisiscore-1.12.2-6.3.0.jar                       | None                                     |
        | UCHIJAAAA | malisisdoors         | 1.12.2-7.2.2             | malisisdoors-1.12.2-7.2.2.jar                      | None                                     |
        | UCHIJAAAA | mtrm                 | 1.2.2.30                 | MineTweakerRecipeMaker-1.12.2-1.2.2.30.jar         | None                                     |
        | UCHIJAAAA | morebees             | 1.12.2-1.4.4             | morebees-1.12.2-1.4.4.jar                          | None                                     |
        | UCHIJAAAA | morechickens         | 3.0.0                    | morechickens-1.12.2-3.0.0.jar                      | None                                     |
        | UCHIJAAAA | morpheus             | 1.12-3.3.2               | Morpheus-1.12-3.3.2.jar                            | None                                     |
        | UCHIJAAAA | netherportalfix      | 5.3.13                   | NetherPortalFix_1.12.1-5.3.13.jar                  | None                                     |
        | UCHIJAAAA | openmods             | 0.11.4                   | OpenModsLib-1.12.2-0.11.4.jar                      | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
        | UCHIJAAAA | openblocks           | 1.7.4                    | OpenBlocks-1.12.2-1.7.4.jar                        | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
        | UCHIJAAAA | opencomputers        | 1.7.1.43                 | OpenComputers-MC1.12.1-1.7.1.43.jar                | None                                     |
        | UCHIJAAAA | openterraingenerator | v4                       | OpenTerrainGenerator-1.12.2 - v4.jar               | e9f7847a78c5342af5b0a9e04e5abc0b554d69e0 |
        | UCHIJAAAA | harvestcraft         | 1.12.2b                  | Pam's HarvestCraft 1.12.2b - Re-Balance Update.jar | None                                     |
        | UCHIJAAAA | reborncore           | 3.6.1.183                | RebornCore-1.12.2-3.6.1.183-universal.jar          | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
        | UCHIJAAAA | quantumstorage       | 4.4.6                    | QuantumStorage-1.12-4.4.6.jar                      | None                                     |
        | UCHIJAAAA | reccomplex           | 1.4.6                    | RecurrentComplex-1.4.6.jar                         | None                                     |
        | UCHIJAAAA | rftools              | 7.22                     | rftools-1.12-7.22.jar                              | None                                     |
        | UCHIJAAAA | rftoolscontrol       | 1.8.0                    | rftoolsctrl-1.12-1.8.0.jar                         | None                                     |
        | UCHIJAAAA | roots                | 0.104                    | roots-2-0.104.jar                                  | None                                     |
        | UCHIJAAAA | snad                 | 1.12.1-1.7.09.16a        | Snad-1.12.1-1.7.09.16a.jar                         | None                                     |
        | UCHIJAAAA | thermalcultivation   | 0.1.3                    | ThermalCultivation-1.12.2-0.1.3.11-universal.jar   | None                                     |
        | UCHIJAAAA | thermaldynamics      | 2.3.8                    | ThermalDynamics-1.12.2-2.3.8.16-universal.jar      | None                                     |
        | UCHIJAAAA | thermalexpansion     | 5.3.8                    | ThermalExpansion-1.12.2-5.3.8.38-universal.jar     | None                                     |
        | UCHIJAAAA | torchmaster          | 1.6.1.53                 | torchmaster_1.12.2-1.6.1.53.jar                    | 5e9a436b366831c8f54a7e80b015784da69278c6 |
        | UCHIJAAAA | usefulnullifiers     | 1.4.1                    | usefulnullifiers-1.4.1.jar                         | None                                     |
        | UCHIJAAAA | wanionlib            | 1.12.2-1.4               | WanionLib-1.12.2-1.4.jar                           | None                                     |
        | UCHIJAAAA | wawla                | 2.5.246                  | Wawla-1.12.2-2.5.246.jar                           | d476d1b22b218a10d845928d1665d45fce301b27 |
        | UCHIJAAAA | worldedit            | 6.1.8                    | worldedit-forge-mc1.12-6.1.8-dist.jar              | None                                     |
        | UCHIJAAAA | unidict              | 1.12.2-2.0               | UniDict-1.12.2-2.0.jar                             | None                                     |
        | UD        | mdecore-core         | 1.0                      | minecraft.jar                                      | None                                     |

        Loaded coremods (and transformers):
IELoadingPlugin (ImmersiveEngineering-0.12-75-core.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
OTGCorePlugin (OTG-Core.jar)
  com.pg85.otg.forge.asm.OTGClassTransformer
IELoadingPlugin (ImmersiveEngineering-0.12-76-core.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
CTMCorePlugin (CTM-MC1.12-0.2.3.9.jar)
  team.chisel.ctm.client.asm.CTMTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.3.0.jar)

CoreMod (Aroma1997Core-1.12.2-1.3.0.2.jar)

OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.4.jar)
  openmods.core.OpenModsClassTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  lumien.resourceloader.asm.ClassTransformer
ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.5.jar)
  shetiphian.asm.ClassTransformer
TransformerLoader (OpenComputers-MC1.12.1-1.7.1.43.jar)
  li.cil.oc.common.asm.ClassTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)

**Comment by GenDeathrow** [comment]
fixed on my dev branch, will get something out in next day or so.
