### ISSUE TITLE
Dupication of Eggs

### ISSUE THREAD

**Issue by GenDeathrow** [GenDeathrow/Hatchery#136]
https://minecraft.curseforge.com/projects/eggblock/issues/4

Ok.. this will be fixed next update.

**Comment by GenDeathrow** [comment]
https://github.com/GenDeathrow/Hatchery/tree/368b6af76bf4cf42b7cb010d20dd1cbf95011ae9

**Comment by IamAlathe** [comment]
I was just coming to report this bug.  Glad to see it's already here.

**Comment by GenDeathrow** [comment]
yeah and hoping to get the update out today soon
