### ISSUE TITLE
[Sponge 1.12.2]Animal Net in servers cannot release chicken

### ISSUE THREAD

**Issue by Pythonic-Rainbow** [GenDeathrow/Hatchery#138]
It is a very weird bug,

I am using Forge 1.12.2 build 2600
Sponge 1.12.2 latest
LuckyPerms for Sponge
GriefPrevention
WorldEdit for Forge

1.I tested my modpack in singleplayer, [works fine](https://youtu.be/vvfycRrQ49w)
2. This is how it looks in our server https://youtu.be/Ps7Jt-hCA9k

The videos seem a bit lag due to my iGPU , however the difference between two videos are still obvious.

**Comment by GenDeathrow** [comment]
I'll look at it, but wont promise anything if its a sponge related issue.

**Comment by Pythonic-Rainbow** [comment]
I guess its not related to sponge as the house that i tested is not claimed yet.

**Comment by Pythonic-Rainbow** [comment]
I recognised that 

1.Sometimes when rightclicking random places, the net seems to released but immediately catch a chicken again.(I think the 2nd video has an example). It feels like there is an invisible chicken.

2.The bugged nets have 2 NBT tags.
![image](https://user-images.githubusercontent.com/25037295/35324990-64fffb6e-012d-11e8-952e-5c257ebd4747.png)

**Comment by Pythonic-Rainbow** [comment]
Well I am wrong.
I removed Sponge and the net worked as expected.
It'll be nice if you still take a look into it.
Shall I create an issue in Sponge?

**Comment by Pythonic-Rainbow** [comment]
thank you for your attention then!

**Comment by Pythonic-Rainbow** [comment]
Can u send me the link of the Sponge issue you created?

**Comment by GenDeathrow** [comment]
I thought you were creating the sponge issue?

**Comment by Pythonic-Rainbow** [comment]
oh you mean to let me create an issue? lol I misunderstood u
k I will now go and create one

**Comment by ryantheleach** [comment]
@Pythonic-Rainbow What version of Sponge are you using, please do not say latest as we have 2 Streams

**Comment by Pythonic-Rainbow** [comment]
@ryantheleach it should be 1.12.2-2555-7.1.0-BETA-2851 or 2847

**Comment by GenDeathrow** [comment]
Closing this for now atm.
