### ISSUE TITLE
[Feature Request] Blacklist/Whitelist for Feeder

### ISSUE THREAD

**Issue by Boolyman** [GenDeathrow/Hatchery#139]
Tossing a bunch of seeds into the feeder is overly simple.  This makes using Chicken Feed crafted from Feather Meal a bit pointless.  I would like my pack players to HAVE to use your Feather Meal/Shredder processing.  So can you add an option to the config that only allows Chicken Feed to be used in the feeder?

**Comment by GenDeathrow** [comment]
Actually not a bad idea @Boolyman. I will put it on my list of todo's

**Comment by GenDeathrow** [comment]
its just a simple boolean no whitelisting for now.
