### ISSUE TITLE
Chickens don't age when in Nesting Pen

### ISSUE THREAD

**Issue by NightmareElmo** [GenDeathrow/Hatchery#14]
if you put a chick in the nesting pen, it stays a chick, unless you remove it and once you either place it back in the nesting pen or in the wild it will age up immediately if it is old enough to do so

**Comment by GenDeathrow** [comment]
They actualky they do age, but its a server client sync issue. I just need to set it up to send update if thw chicken turns into an adult. Its on the list.

**Comment by GenDeathrow** [comment]
At some point I will be fixing this, but it will break a lot.  The nesting pens code could have been done a lot better.

**Comment by GenDeathrow** [comment]
I finally figured this visual bug out. client would get an update from the server, but didn't know what to do after that. will work for next version

**Comment by GenDeathrow** [comment]
0.2.4
