### ISSUE TITLE
[1.12.2] Information listed in JEI doubled up...

### ISSUE THREAD

**Issue by PhoenixRiver** [GenDeathrow/Hatchery#140]
Version: hatchery-1.12.2-2.1.2

In JEI the Info tab on recipes for the shredder and methane digester generator (and I think one or two others) have their information doubled up, i.e. one page of information shows twice showing the same page twice, two pages shows the information and then a second two pages with the same information a second time... it doesn't happen with everything in hatchery, just some and definitely the above mentioned - I'll add more when I find them if that's okay?

**Comment by GenDeathrow** [comment]
thanks I will take a look at that when I get the chance.
