### ISSUE TITLE
[1.12.2] Compat issue with Immersive Engineering.

### ISSUE THREAD

**Issue by PhoenixRiver** [GenDeathrow/Hatchery#146]
When just Hatchery and Immersive Engineering are installed (with forge) plants no longer grow in the Garden Cloche (Belljar) from Immersive Engineering (IE). The problem seems to be with the fertiliser system in the cloche, it sticks at zero rather than refilling and allowing the plant inside to grow. This is a possible overlap problem with the fertilised dirt block code?

See IM issue 2883:
BluSunrize/ImmersiveEngineering#2883

Mods:
Forge: forge1.12.2-14.23.2.2611
ImmersiveEngineering: 0.12-78
Hatchery: 1.12.2-2.1.2

**Comment by PhoenixRiver** [comment]
Hatchery has a liquid_fertilizer liquid registered here:
/src/main/java/com/gendeathrow/hatchery/fluid/LiquidFertilizer.java
as well as fertilized_dirt and _farmland blocks here and here:
/src/main/java/com/gendeathrow/hatchery/block/fertilizedDirt/FertilizedDirt.java
/src/main/java/com/gendeathrow/hatchery/block/fertilizedDirt/FertilizedFarmland.java

Immersive Engineering seems to search for OreDictionary entries for fertilizer items here:
/src/main/java/blusunrize/immersiveengineering/api/tool/BelljarHandler.java    -    line 414

Is this potentially a problem?

(I don't know if "OreDictionary.itemMatches(bonemeal,fertilizer,true)" does substring matches or not and I'm out of time for the moment - apologies).

**Comment by GenDeathrow** [comment]
I have not registered hatchery fertilizer to IE at all. so it shouldn't be causing any issue.

**Comment by GenDeathrow** [comment]
Ok I just recreated this, With all the same versions pulled from curse. The Garden Cloche worked as intended. So I'm not sure whats happening but it doesn't look like its hatchery,

**Comment by PhoenixRiver** [comment]
Here is my setup recreated in a brand new world with only hatchery, IE and forge.
![2018-03-19_15 17 08](https://user-images.githubusercontent.com/5155303/37604526-171da69a-2b89-11e8-9006-012ef384a18b.png)
![2018-03-19_15 17 16](https://user-images.githubusercontent.com/5155303/37604536-1c2432da-2b89-11e8-9ed2-106f79afd019.png)

Note that the column next to the water level is empty - this should be full. Note I'm also only using a vanilla carrot and vanilla dirt.

What I was guessing was the problem is a name clash between things created in hatchery and things used in IE... however I have not read anything more than a few hundred lines of each code base so this is a guess based on experience rather than any real knowledge of either code base.

If you can show me your setup maybe I can put that together and confirm it's not a problem for me - maybe there is something to do with my setup (forge or minecraft) that is a problem I need to fix.

**Comment by GenDeathrow** [comment]
You have to place bone meal in the box under the water column for fertilizer.

**Comment by GenDeathrow** [comment]
![image](https://user-images.githubusercontent.com/3720710/37607438-0509c25e-2b66-11e8-8472-476992c23931.png)

![image](https://user-images.githubusercontent.com/3720710/37607457-1766e670-2b66-11e8-8c18-0da12c485b12.png)

**Comment by PhoenixRiver** [comment]
There isn't actually a definite need for fertiliser in the cloche, it only speeds things up but it turns out in my setup my pump switch is adjacent to the cloche as well as the pump and so sends both a redstone signal... in the case of the pump that means it turns on but in the case of the cloche (as with most of IEs stuff) it tells it to stop. Problem solved as this was an ID10t problem *sigh*

Apologies and thank you for your help.

**Comment by GenDeathrow** [comment]
np.. glad you got it wokred out.
