### ISSUE TITLE
[Feature Request] Option to control manure amount from wild chickens

### ISSUE THREAD

**Issue by AdaraChristine** [GenDeathrow/Hatchery#148]
Hi!
The amount of generated manure by "wild" chickens gets out of control and adds lag to my pack's servers. An option to turn this down and off would be fantastic!
Thanks for your hard work on this nice mod

**Comment by Syndaryl** [comment]
I'd like also to control the amount of manure generated by bred chickens (or chickens in general) - to control difficulty.

**Comment by GenDeathrow** [comment]
This one is in the works already. I'm currently working on a change for how manure is handled.

**Comment by GenDeathrow** [comment]
So apparently there was a bug and it was over producing manure.  Im thinking of changing the the manure production to work like this. Wild chickens will produce super slow, while chickens that have a chicken feeder near by will produce faster.
