### ISSUE TITLE
Animal net doesn't get emptied when placing chicken in nesting pen.

### ISSUE THREAD

**Issue by Zeldon567** [GenDeathrow/Hatchery#152]
If placed on the ground, the animal net is still named as if it has an animal in it and is no longer functional. Using it on nesting pens duplicates the chicken.

**Comment by Zeldon567** [comment]
GitHub noob here. How do I add a label?

**Comment by GenDeathrow** [comment]
you cant add lable's only me. I need to know what mod version, minecraft version, and are you using spongeforge?

**Comment by Zeldon567** [comment]
Minecraft version 1.12.2, mod version v2.1.2, spongeforge is being run. FoamFix anarchy is in the pack.

**Comment by Zeldon567** [comment]
I have tested Chickens and Hatchery in a clean pack and can confirm it works as intended, Will investigate the source of the issue.

**Comment by Zeldon567** [comment]
Unfortunately nothing is appearing in the logs involving this issue. How irritating.

**Comment by Zeldon567** [comment]
Removing FoamFix had no effect.

**Comment by GenDeathrow** [comment]
Its Sponge.. they have broken my mod so many times. They fix it, than couple versions later its broken again.

**Comment by Zeldon567** [comment]
Bah. Is there a version of Spongeforge that allows your mod to work correctly?

**Comment by Zeldon567** [comment]
On 1.12.2, of course.

**Comment by GenDeathrow** [comment]
no idea.. .tbh.

**Comment by Zeldon567** [comment]
I don't suppose it's something you could easily fix on your end and release an update, is it? Or you would've done it already.

**Comment by Boolyman** [comment]
People playing my pack are having the same issue, using Forge.

**Comment by GenDeathrow** [comment]
no.. best thing to do is report to sponge forge.  The only reason is because im using forge methods. Now im all ways willing to make changes if needed. but I normally don't fix sponge forge issues unless i know for sure it works in forge as intended

**Comment by Wissi** [comment]
We have updated to sponge several version already and still not fixed. As you said in your last comment:
> Now im all ways willing to make changes if needed. but I normally don't fix sponge forge issues unless i know for sure it works in forge as intended

Could you be so gracious as to make that change please? To also let @Zeldon567 know.
Thank you so much, we love your mod and quick responses.

**Comment by GenDeathrow** [comment]
I'm not entirely sure what to do to fix this. The Net contains an Entity NBT, when you click on the pen it places it into the pen, than it erases the NBT data. But whats happening is the NBT isn't throwing a null like it should. The code to remove the chicken is no different whether your placing in a pen or on the ground. So why one works and the other doesn't baffles me. But something interacting with blocks messes up the item.

**Comment by Wissi** [comment]
Problem is neither options clears the net. 
Whether you place in pen or on ground net stays w/mob info and can be infi placed.

**Comment by GenDeathrow** [comment]
I get that, but in my code it clears the net. Its a sponge interaction issue. It works fine in plain forge.
