### ISSUE TITLE
[1.12.2] Chicken Stats In Nesting Pen Not Updating

### ISSUE THREAD

**Issue by thebigcarp321** [GenDeathrow/Hatchery#154]
Hello, I have been playing with Chickens, More Chickens, and Hatchery in the All the Mods 3 pack which uses 1.12.2. I have been playing for a week and have a few dozen chickens in pens and I noticed that since I started breeding Water and Reinforced Iron Chickens that I can no longer get the proper stats to show up when looking at the Chickens in the Hatchery.

Normally I analyze them, they show me something like 5,6,7, I put them in the hatchery and it shows me 5,6,7 in the hatchery. I breed a better one and lets say that its now 10,10,10! I put the 10,10,10 in that hatchery, or ANY hatchery and the stats are stuck on 5,6,7.

I have tried deleting and recreating the pens, the net, the analyzer and I am not able to get it to change. I have also tried reanalyzing the chickens, the hatcheries, etc. I'm not sure how this started or what caused it as it has just happened and it seems to be spreading to other chickens.

Please let me know if there is any other information I can provide.

**Comment by thebigcarp321** [comment]
Just an update during testing today. I confused 2 chickens today so the values i listed above are not valid. It appears to flip values so they are upside down.

Values I will be listed in order of Strength, Gain, Growth.

New example
Silver chicken outside of pen: 3,5,5
Silver Chicken inside of pen: 5,5,3

Another example:
Water Egg outside of pen: 7,6,5
Water egg inside of pen: 5,6,7

Thanks.

**Comment by GenDeathrow** [comment]
ahh.. I prolly just switched the text around.

**Comment by GenDeathrow** [comment]
fixed in next update
