### ISSUE TITLE
Crash on Server - NoClassDefFoundError: com/gendeathrow/hatchery/item/HatcheryEgg

### ISSUE THREAD

**Issue by rckymtnrfc** [GenDeathrow/Hatchery#16]
Seeing this crash on server startup.

http://pastebin.com/UxLjNX2r

**Comment by GenDeathrow** [comment]
Yes I am currently fixing the issue, it has to do with the colored eggs.  Ididn't realized they had changed something in 1.9.

**Comment by GenDeathrow** [comment]
fixed 0.1.11
