### ISSUE TITLE
Can't edit lucky_eggs.json properly. 

### ISSUE THREAD

**Issue by 99Blocks** [GenDeathrow/Hatchery#162]
Hey,

I've been playing around with the Lucky Eggs a bit to provide a loot alternative on my pack but I can't seem to get the json to work with altered drops. 

I've tried with both modded and vanilla items but something isn't adding up. 

Could you provide an example of how a custom drop would work, including where meta data should be and perhaps explaining the different elements of each drop?

Thanks for your time!

**Comment by GenDeathrow** [comment]
paste bin your file and let me see what you have first.

**Comment by 99Blocks** [comment]
No problem. 
I don't actually have a fully edited file because somewhere along the way I reverted to the default list so I could get the pack to testers.

A sample of the format I'm using is this:

{
  "minecraft:soul_sand:0": {
    "item": "minecraft:soul_sand",
    "minQty": 1,
    "maxQty": 2,
    "weight": 10
  },
  "immersiveengineering:wirecoil:0": {
    "item": "immersiveengineering:wirecoil",
    "minQty": 1,
    "maxQty": 3,
    "weight": 13
  },
  "xreliquary:mob_charm_fragment:7": {
    "item": "xreliquary:mob_charm_fragment:7",
    "minQty": 1,
    "maxQty": 2,
    "weight": 14
  }
}

**Comment by GenDeathrow** [comment]
Dont think I will be able to get an update out atm for this particular issues. are you getting any errors in your log files pertaining to json parse issue or anything for hatchery?

**Comment by GenDeathrow** [comment]
Hey I'm not sure whats happening, everything works fine on my end. I know I hadn't gotten to this in a long time. Modding hasn't been a priority atm. I even added in the soul sand you used and it worked fine. I realize it may not matter anymore since its been so long. but just giving you an update.
