### ISSUE TITLE
They did not work: sprayer, sand chicken, log chicken, smart and flint

### ISSUE THREAD

**Issue by AberracjaA** [GenDeathrow/Hatchery#164]
Hello.
Unfortunately, a few things do not work for me.
I can not create a sand chicken, log, smart and flint.
I can't also fill the spray.
I use Minecraft 1.12.2.
Where can I search for a mistake?

**Comment by GenDeathrow** [comment]
I'll answer best I can.
 sand chicken, log chicken, and flint are found chickens that spawn in the world. And smart chicken is just hitting a regular chicken with a book. By the way this is the Chickens Mod not Hatchery, but I work both. 

2. sprayer needs more explanation.But You currently fill the sprayer inside the fertilizer mixer. or thur any mod that will fill a liquid container. 

I have some info for hatchery here.  I cant remember if everything is up-to-date but it should be pretty close. 
https://github.com/GenDeathrow/Hatchery/wiki
