### ISSUE TITLE
server problem with animal net,egg nest, and nesting box

### ISSUE THREAD

**Issue by angiebabe196** [GenDeathrow/Hatchery#165]
there is a problem with the mod duplicating chickens and making the net a one time use as well as a problem with the egg nest not registering there is a nest in and the nesting boxes no longer allowing breeding I have played with this mod in single player but on my server it has not been working no matter how I try the mods . thanks in advance .

**Comment by angiebabe196** [comment]
i am using sponge and 1.12.2 version .

**Comment by GenDeathrow** [comment]
Yeah its a sponge issue..My only suggestion is remove sponge for now.

https://github.com/GenDeathrow/Hatchery/issues?q=label%3A%22Sponge+Issue%22+is%3Aclosed
