### ISSUE TITLE
Throwing egg to hatch spawns vanilla chicken

### ISSUE THREAD

**Issue by Sunekaer** [GenDeathrow/Hatchery#166]
Hey 

Can you help me with this issue?
Throwing egg to hatch spawns vanilla chicken

"Can Throw Eggs" is set to "true" in config 

https://github.com/Sunekaer/stoneBlock/issues/98

Thank you

**Comment by GenDeathrow** [comment]
I'll look into it. can you tell me the MC and hatchery versions please?

**Comment by Sunekaer** [comment]
hatchery-1.12.2-2.1.2
forge-1.12.2-14.23.4.2707

**Comment by GenDeathrow** [comment]
So I cant seem to recreate this with just the hatchery/chickens/and forge version. Are you able to recreate this with just those mods?

**Comment by Sunekaer** [comment]
I'll have to test, I just know that multiple people have come to my saying they have that problem, and I can't figure out why

**Comment by Sunekaer** [comment]
Okay i tested with 
forge 2707
Chickens 
Hatchery
Not ENough Wands for the speeding up breeding
and McJtyLib for NEW

so taking the hatchery Redstone egg dropped from the Redstone chicken in Nesting Pen, throwing it in Creative spawns a Redstone chicken BUT throwing it in Survival mode I get a vanilla chicken

**Comment by GenDeathrow** [comment]
hum.. now that's interesting. I was able to replicate that. That makes no sense at all.  I look into it.

**Comment by GenDeathrow** [comment]
This is a strange error. nbt has a function that says if it has a tag.. for some reason in creative it returns true.. but pure survival worlds it returns false.  That's a major issue that shouldn't happen.  Either way Im created my own override for it. and I will use it for now until I can find why its doing that. and report it.

**Comment by Sunekaer** [comment]
How long to you push out an update to fix this? (Currently working on an update for my pack, just wanna know if I can get this fix in this one)

**Comment by GenDeathrow** [comment]
well hopping tomorrow night, mainly cause I will be out of town for 2 days. so trying to get it out soon.

**Comment by GenDeathrow** [comment]
I pushed the update last night, but just waiting for it to actually get reviewed. Got to wait for the curse forge guys now. Hopefully it gets passed cause I'll be out of town. its version 2.1.3.
