### ISSUE TITLE
Ticking Block Entity

### ISSUE THREAD

**Issue by sdaddy** [GenDeathrow/Hatchery#17]
It seems whenever a Flint chicken from the Chickens mod lays something in a nest pen my server crashes. If this is a bug with Chickens, disregard this report. That mod hasn't been updated since May so I was hoping it was a Hatchery bug. :)

http://pastebin.com/raw/K8FN5bqy

**Comment by GenDeathrow** [comment]
it isn't a hatchery issue, And it does appear that the chickens mod has halted. Now I have watched Darkosto play this mod and that mod on stream with out issues. Have you tried breaking the pen and replacing it.. and is this the latest version?

**Comment by GenDeathrow** [comment]
No dont get me wrong it does happen inside my nesting pen, but the error happens in chickens mod. Maybe for a fix, I could try and catch errors.

**Comment by sdaddy** [comment]
I think I've narrowed down the problem. It seems it happens when I have a flint chicken next to a vanilla chicken. I'm guessing they're trying to mate and it's crashing.

**Comment by GenDeathrow** [comment]
Thanks for the report

**Comment by Gayanfalor** [comment]
Hello, 

it seems we are having the same issues here in our server but after the crash the server cant reboot.

Here is the crashlog    https://drive.google.com/open?id=0B9iNaLFrsdUpcEtld2x0QkR1MTQ


Before the crash i had normal setup with 2 nestpens with normal chickens in it and 3-4 sand and flint chickens on the gorund, i craftted some more nestpens to put flint and sand chickens in it to get stuff in the nest and not on the ground spamming it.

And i went ot a dungeon under my house and it crashed.

Btw i tested to reproduce it in solo but i cant put a chicken in nestpen when already a chicken is in a nestpen just next to it

**Comment by GenDeathrow** [comment]
@Gayanfalor  thats just strange. I have some mods that need some work, and Im hoping to get back to this mod soon. But I got some major issues in another mod that need fixed. I will try messing with this.

**Comment by GenDeathrow** [comment]
This should be fixed on version **0.1.14**
