### ISSUE TITLE
Error when trying to fill Fertilizer Spray

### ISSUE THREAD

**Issue by Lonewolf22113** [GenDeathrow/Hatchery#170]
So I crafted the mixer and Spray, made liquid fertilizer dropped in a hole in ground and right clicked it with the Spray equipped, but I get an error message and the Fertilizer Spray is not getting filled and I lose the liquid Fertilizer, but it does not crash my game.
This is the Error Log it Gives me:

> ---- Minecraft Crash Report ----
> // Don't do that.
> 
> Time: 2018-10-26 17:33:19 CEST
> Description: Error executing task
> 
> java.util.concurrent.ExecutionException: java.lang.ClassCastException: net.minecraftforge.fluids.FluidActionResult cannot be cast to net.minecraft.item.ItemStack
>     at java.util.concurrent.FutureTask.report(Unknown Source)
>     at java.util.concurrent.FutureTask.get(Unknown Source)
>     at net.minecraft.util.Util.runTask(SourceFile:531)
>     at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723)
>     at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
>     at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185)
>     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
>     at java.lang.Thread.run(Unknown Source)
> Caused by: java.lang.ClassCastException: net.minecraftforge.fluids.FluidActionResult cannot be cast to net.minecraft.item.ItemStack
>     at net.minecraft.server.management.PlayerInteractionManager.processRightClick(PlayerInteractionManager.java:359)
>     at net.minecraft.network.NetHandlerPlayServer.processTryUseItem(NetHandlerPlayServer.java:765)
>     at net.minecraft.network.play.client.CPacketPlayerTryUseItem.processPacket(SourceFile:32)
>     at net.minecraft.network.play.client.CPacketPlayerTryUseItem.processPacket(SourceFile:9)
>     at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
>     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
>     at java.util.concurrent.FutureTask.run(Unknown Source)
>     at net.minecraft.util.Util.runTask(SourceFile:529)
>     ... 5 more
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- System Details --
>   Minecraft Version: 1.12.2
>   Operating System: Windows 10 (amd64) version 10.0
>   Java Version: 1.8.0_191, Oracle Corporation
>   Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
>   Memory: 394221288 bytes (375 MB) / 2592727040 bytes (2472 MB) up to 3996385280 bytes (3811 MB)
>   JVM Flags: 3 total; -Xmn128M -Xmx3824M -XX:+UseConcMarkSweepGC
>   IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
>   FML: MCP 9.42 Powered by Forge 14.23.5.2768 75 mods loaded, 75 mods active
>        States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
>        
>        | State     | ID                   | Version                  | Source                                          | Signature                                |
>        |:--------- |:-------------------- |:------------------------ |:----------------------------------------------- |:---------------------------------------- |
>        | UCHIJAAAA | minecraft            | 1.12.2                   | minecraft.jar                                   | None                                     |
>        | UCHIJAAAA | mcp                  | 9.42                     | minecraft.jar                                   | None                                     |
>        | UCHIJAAAA | FML                  | 8.0.99.99                | forge-1.12.2-14.23.5.2768.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
>        | UCHIJAAAA | forge                | 14.23.5.2768             | forge-1.12.2-14.23.5.2768.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
>        | UCHIJAAAA | smoothfontcore       | 1.12.2-1.14              | minecraft.jar                                   | None                                     |
>        | UCHIJAAAA | smoothfont           | 1.12.2-1.15              | SmoothFont-1.12.2-1.15.jar                      | None                                     |
>        | UCHIJAAAA | movillages           | 1.5.4                    | [1.12]MoVillages-1.5.4.jar                      | None                                     |
>        | UCHIJAAAA | gobblecore           | 1.12-0.1.6.35            | GobbleCore-1.12-0.1.6.35.jar                    | None                                     |
>        | UCHIJAAAA | charcoalblock        | 1.1                      | A Block of Charcoal-1.1.jar                     | None                                     |
>        | UCHIJAAAA | actuallyadditions    | 1.12.2-r135              | ActuallyAdditions-1.12.2-r135.jar               | None                                     |
>        | UCHIJAAAA | baubles              | 1.5.2                    | Baubles-1.12-1.5.2.jar                          | None                                     |
>        | UCHIJAAAA | actuallybaubles      | 1.1                      | ActuallyBaubles-1.12-1.1.jar                    | None                                     |
>        | UCHIJAAAA | animalium            | 0.3.7                    | Animalium-0.3.7.jar                             | None                                     |
>        | UCHIJAAAA | antiqueatlas         | 4.4.9                    | antiqueatlas-1.12.2-4.4.9.jar                   | None                                     |
>        | UCHIJAAAA | antiqueatlasoverlay  | 1.2                      | antiqueatlas-1.12.2-4.4.9.jar                   | None                                     |
>        | UCHIJAAAA | examplemod           | 1.0                      | antiqueatlas-1.12.2-4.4.9.jar                   | None                                     |
>        | UCHIJAAAA | applecore            | 3.1.1                    | AppleCore-mc1.12.2-3.1.1.jar                    | None                                     |
>        | UCHIJAAAA | jei                  | 4.13.1.220               | jei_1.12.2-4.13.1.220.jar                       | None                                     |
>        | UCHIJAAAA | appleskin            | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                      | None                                     |
>        | UCHIJAAAA | crafttweaker         | 4.1.11                   | CraftTweaker2-1.12-4.1.11.jar                   | None                                     |
>        | UCHIJAAAA | armoreablemobs       | 1.1.2                    | armoreablemobs-1.12-1.1.6-4.jar                 | None                                     |
>        | UCHIJAAAA | astikoor             | 1.1.0                    | astikoor_horse-carts-1.1.0a.jar                 | None                                     |
>        | UCHIJAAAA | betteradvancements   | 0.0.7.42                 | BetterAdvancements-1.12.2-0.0.7.42.jar          | None                                     |
>        | UCHIJAAAA | betterbuilderswands  | 0.11.1                   | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar | None                                     |
>        | UCHIJAAAA | bonsaitrees          | 1.0.5                    | bonsaitrees-1.0.5-b77.jar                       | None                                     |
>        | UCHIJAAAA | bookshelf            | 2.3.566                  | Bookshelf-1.12.2-2.3.566.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
>        | UCHIJAAAA | carryon              | 1.9                      | CarryOn MC1.12.2 v1.9.jar                       | None                                     |
>        | UCHIJAAAA | chameleon            | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                        | None                                     |
>        | UCHIJAAAA | chancecubes          | 1.12.2-3.2.2.237         | ChanceCubes-1.12.2-3.2.2.237.jar                | None                                     |
>        | UCHIJAAAA | chickens             | 6.1.0                    | chickens-6.1.0.jar                              | None                                     |
>        | UCHIJAAAA | clumps               | 3.1.1                    | Clumps-3.1.1.jar                                | None                                     |
>        | UCHIJAAAA | codechickenlib       | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
>        | UCHIJAAAA | cookingforblockheads | 6.3.26                   | CookingForBlockheads_1.12.2-6.3.26.jar          | None                                     |
>        | UCHIJAAAA | ctgui                | 1.0.0                    | CraftTweaker2-1.12-4.1.11.jar                   | None                                     |
>        | UCHIJAAAA | crafttweakerjei      | 2.0.2                    | CraftTweaker2-1.12-4.1.11.jar                   | None                                     |
>        | UCHIJAAAA | ptrmodellib          | 1.0.3                    | PTRLib-1.0.3.jar                                | None                                     |
>        | UCHIJAAAA | props                | 2.6.2                    | Decocraft-2.6.2_1.12.2.jar                      | None                                     |
>        | UCHIJAAAA | elevatorid           | 1.3.6                    | ElevatorMod-1.12.2-1.3.6.jar                    | None                                     |
>        | UCHIJAAAA | enchdesc             | 1.1.8                    | EnchantmentDescriptions-1.12.2-1.1.8.jar        | d476d1b22b218a10d845928d1665d45fce301b27 |
>        | UCHIJAAAA | fbp                  | 2.4.0                    | FancyBlockParticles-1.12.x-2.4.0.jar            | None                                     |
>        | UCHIJAAAA | farmingforblockheads | 3.1.17                   | FarmingForBlockheads_1.12.2-3.1.17.jar          | None                                     |
>        | UCHIJAAAA | farseek              | 2.3                      | Farseek-1.12-2.3.jar                            | None                                     |
>        | UCHIJAAAA | gravestone           | 1.10.1                   | gravestone-1.10.1.jar                           | None                                     |
>        | UCHIJAAAA | hatchery             | 2.1.4                    | hatchery-1.12.2-2.1.4.jar                       | None                                     |
>        | UCHIJAAAA | headcrumbs           | 2.0.4                    | Headcrumbs-1.12.2-2.0.4.15.jar                  | None                                     |
>        | UCHIJAAAA | waila                | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                     | None                                     |
>        | UCHIJAAAA | improvedbackpacks    | 1.12.2-1.2.0.3           | ImprovedBackpacks-1.12.2-1.2.0.3.jar            | None                                     |
>        | UCHIJAAAA | jeresources          | 0.8.5.27                 | JustEnoughResources-1.12.2-0.8.5.27.jar         | None                                     |
>        | UCHIJAAAA | mantle               | 1.12-1.3.2.24            | Mantle-1.12-1.3.2.24.jar                        | None                                     |
>        | UCHIJAAAA | tconstruct           | 1.12.2-2.10.1.84         | TConstruct-1.12.2-2.10.1.84.jar                 | None                                     |
>        | UCHIJAAAA | morechickens         | 3.2.0                    | morechickens-1.12.2-3.2.0.jar                   | None                                     |
>        | UCHIJAAAA | natura               | 1.12.2-4.3.2.49          | natura-1.12.2-4.3.2.49.jar                      | None                                     |
>        | UCHIJAAAA | naturescompass       | 1.5.1                    | NaturesCompass-1.12.2-1.5.1.jar                 | None                                     |
>        | UCHIJAAAA | neat                 | 1.4-15                   | Neat 1.4-15.jar                                 | None                                     |
>        | UCHIJAAAA | norecipebook         | 1.2.1                    | noRecipeBook_v1.2.2formc1.12.2.jar              | None                                     |
>        | UCHIJAAAA | nei                  | 2.4.2                    | NotEnoughItems-1.12.2-2.4.2.240-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
>        | UCHIJAAAA | samsocean            | 1.0.1                    | OceanFloor-1.12-1.0.1.jar                       | None                                     |
>        | UCHIJAAAA | oreexcavation        | 1.4.118                  | OreExcavation-1.4.118.jar                       | None                                     |
>        | UCHIJAAAA | quickleafdecay       | 1.2.4                    | QuickLeafDecay-MC1.12.1-1.2.4.jar               | None                                     |
>        | UCHIJAAAA | realdrops            | 1.2.12                   | RealisticItemDrops-1.2.12.jar                   | None                                     |
>        | UCHIJAAAA | repose               | 1.6.1                    | Repose-1.12-1.6.1.jar                           | None                                     |
>        | UCHIJAAAA | rustic               | 1.0.5                    | rustic-1.0.5.jar                                | None                                     |
>        | UCHIJAAAA | scannable            | 1.6.3.19                 | Scannable-MC1.12-1.6.3.19.jar                   | None                                     |
>        | UCHIJAAAA | simplyarrows         | 1.0.4                    | SimplyArrows-1.12.2-1.0.4.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
>        | UCHIJAAAA | snad                 | 1.12.1-1.7.09.16a        | Snad-1.12.1-1.7.09.16a.jar                      | None                                     |
>        | UCHIJAAAA | stg                  | 1.12.2-1.2.3             | stg-1.12.2-1.2.3.jar                            | None                                     |
>        | UCHIJAAAA | storagedrawers       | 1.12-5.3.5               | StorageDrawers-1.12.2-5.3.6.jar                 | None                                     |
>        | UCHIJAAAA | streams              | 0.4.4                    | Streams-1.12-0.4.4.jar                          | None                                     |
>        | UCHIJAAAA | tinkertoolleveling   | 1.12.2-1.0.5.DEV.30c7957 | TinkerToolLeveling-1.12.2-1.0.5.jar             | None                                     |
>        | UCHIJAAAA | vanillafix           | 1.0.9-97                 | VanillaFix-1.0.9-97.jar                         | None                                     |
>        | UCHIJAAAA | vc                   | 5.6.1                    | ViesCraft-1.12.2-5.6.1.jar                      | None                                     |
>        | UCHIJAAAA | waddles              | 0.6.0                    | Waddles-1.12.2-0.6.0.jar                        | None                                     |
>        | UCHIJAAAA | wailaharvestability  | 1.1.12                   | WailaHarvestability-mc1.12-1.1.12.jar           | None                                     |
>        | UCHIJAAAA | wildcrops            | 1.0.1                    | WildCrops-1.12-1.0.1.jar                        | None                                     |
>        | UCHIJAAAA | yoyos                | 1.12.2-1.2.2.20          | yoyos_1.12.2-1.2.2.20.jar                       | None                                     |
>   Loaded coremods (and transformers): FarseekCoreMod (Farseek-1.12-2.3.jar)
>                                         farseek.core.FarseekClassTransformer
>                                       VanillaFixLoadingPlugin (VanillaFix-1.0.9-97.jar)
>                                         
>                                       AppleCore (AppleCore-mc1.12.2-3.1.1.jar)
>                                         squeek.applecore.asm.TransformerModuleHandler
>                                       CorePlugin (SmoothFont-1.12.2-1.15.jar)
>                                         bre.smoothfont.asm.Transformer
>   GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
>   Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
>                                    - TinkerWorld (Enabled/Not Forced)
>                                    - TinkerTools (Enabled/Not Forced)
>                                    - TinkerHarvestTools (Enabled/Forced)
>                                    - TinkerMeleeWeapons (Enabled/Forced)
>                                    - TinkerRangedWeapons (Enabled/Forced)
>                                    - TinkerModifiers (Enabled/Forced)
>                                    - TinkerSmeltery (Enabled/Not Forced)
>                                    - TinkerGadgets (Enabled/Not Forced)
>                                    - TinkerOredict (Enabled/Forced)
>                                    - TinkerIntegration (Enabled/Forced)
>                                    - TinkerFluids (Enabled/Forced)
>                                    - TinkerMaterials (Enabled/Forced)
>                                    - TinkerModelRegister (Enabled/Forced)
>                                    - wailaIntegration (Enabled/Not Forced)
>   Pulsar/natura loaded Pulses: - NaturaCommons (Enabled/Forced)
>                                - NaturaOverworld (Enabled/Not Forced)
>                                - NaturaNether (Enabled/Not Forced)
>                                - NaturaDecorative (Enabled/Not Forced)
>                                - NaturaTools (Enabled/Not Forced)
>                                - NaturaEntities (Enabled/Not Forced)
>                                - NaturaOredict (Enabled/Forced)
>                                - NaturaWorld (Enabled/Not Forced)
>   Suspected Mods: Unknown

**Comment by Lonewolf22113** [comment]
anyone?

**Comment by GenDeathrow** [comment]
never actually saw this till you typed that comment. been busy this last couple months. but I'll look at it.. but you can fill it inside the fertilizer mixer or with any mod that allows fluids to be filled from.
