### ISSUE TITLE
Crash When Placing an Egg into the Egg Nest

### ISSUE THREAD

**Issue by Mivao** [GenDeathrow/Hatchery#171]
Basically as the title suggests. Totally fresh install - only Chickens/HWYLA/Hatchery/NEI.
Crash Report is attached. Thanks for the mod.

[Error Report.txt](https://github.com/GenDeathrow/Hatchery/files/2568475/Error.Report.txt)

**Comment by GenDeathrow** [comment]
Update your forge to the latest.. I make sure to put in a minimum version  in the mod to tell ya.

**Comment by JuanDavidSolano** [comment]
hello, i have the same issue i already updated the forge to the last version :c the only thing that crash is the client, the server didnt crash
