### ISSUE TITLE
Fertilizer Mixer consumes Manure while idle and independently of production

### ISSUE THREAD

**Issue by Lykrast** [GenDeathrow/Hatchery#175]
The Fertilizer Mixer constantly consumes Manure it has started to process, regardless of being idle or working: https://github.com/GenDeathrow/Hatchery/blob/1.12/src/main/java/com/gendeathrow/hatchery/block/fertilizermixer/FertilizerMixerTileEntity.java#L188

This means that the amount of Liquid Fertilizer you get from 1 Manure depends on your speed upgrades:
* Unpowered: 50 mB/Manure, 560 mB/Block
* Powered: 82 mB/Manure, 932 mB/Block
* Tier 1 speed: 91 mB/Manure, 1020 mB/Block
* Tier 2 speed: 92 mB/Manure, 1050 mB/Block
* Tier 3 speed: 100 mB/Manure, 1080 mB/Block

Which feels really weird that the Speed Upgrades would increase manure effiency.

**Comment by GenDeathrow** [comment]
yeah that wasn't actually intended. thanks for noticing that.
