### ISSUE TITLE
Animania chicks spam adult chickens while inside the nesting pence

### ISSUE THREAD

**Issue by mser7** [GenDeathrow/Hatchery#179]
Put an animania chick in the pence, and wait till its time to grow up, what you will see instead is a chicken spawned outside of the block, and the chick is still inside of it, bigger than before. I think it is because when the chick grow up, it transform into a different mob, in this case it is unable to, and will keep spamming chickens while being kept inside the pence.
![2019-02-03_10 47 40](https://user-images.githubusercontent.com/22555489/52172822-f8e19380-27a9-11e9-91c6-3cf0fdee3550.png)
![2019-02-03_10 47 44](https://user-images.githubusercontent.com/22555489/52172823-f97a2a00-27a9-11e9-9334-eb006a90b40f.png)
![2019-02-03_10 48 01](https://user-images.githubusercontent.com/22555489/52172824-f97a2a00-27a9-11e9-9ae9-a40e8f9d0242.png)

**Comment by GenDeathrow** [comment]
~~I will look into this, but no promises on this. Animania and my mod have had a few incompatibility issues.  Animania has at least made it so my mod actually accepts them as chickens.~~

Edit: Yeah it looks like the chicken is set to dead in the pen, and a male or female will spawn. I can handle the chicken being set to dead.. but as far as the chicken spawning outside the pen. I cant handle that. I will have no way on knowing if that chicken is suppose to be inside the pen when it spawns, as it is a completely new entity.
