### ISSUE TITLE
Some chickens wont go on the pens

### ISSUE THREAD

**Issue by MrAmericanMike** [GenDeathrow/Hatchery#18]
So I was trying Slime Chickens and the Animal Net wont release them into the pen.

No sure why this is happening or what the mod is looking for to allow them. As some chickens from other mod wont go there neither.

Using Hatchery 0.1.11

**Comment by MrAmericanMike** [comment]
Ohh let me update. Apparently the problem was that Im doing the tests on Creative, and when taking the Pen using the middle click of the mouse, when you place that one down, it's "unusable" as it thinks there is some chicken still there or something.

PS: My customs chickens still wont go in them anyway ;)

**Comment by GenDeathrow** [comment]
try breaking the pen and replacing it. did you happen to update from an older version?

**Comment by MrAmericanMike** [comment]
When picking a fresh new Pen from the creative Tab, it works perfect with all the Chickens from the Chickens mod. Not with custom chickens I have made in a mod.

I'm doing this tests on a brand new world, so I don't think it's related to some update in between.

Maybe the chickens I'm trying to use on the pen aren't the right type of "Chickens" the mod is looking for. I wouldn't worry too much as for sure I will ditch my chickens and use yours once you can make the copper ones and all that ;)

PS: I'm the one that sent you some chickens textures. So if you need any more help, let me know :)

**Comment by GenDeathrow** [comment]
ahh. are you extending off vanilla chickens in your mod? cause you have too. As long as you extend off that chicken your good as gold. Also override the function for the chicken drops too. That way my pens can catch the items.

**Comment by MrAmericanMike** [comment]
Ok, gonna take a look at all that ;) I don't remember if I extended the Vanilla Chicken or not. 

Will try to work on that this week and update you if I get them working on your pens. Thanks a lot for your time and for the great mods ;)

**Comment by GenDeathrow** [comment]
@MrAmericanMike any luck on this?

**Comment by MrAmericanMike** [comment]
Uhhh sorry I totally forgot to do a follow up, gonna make some time for this during the week and let you know. Sorry been busy between internet issues and launching my first ModPack ever on the ATLauncher :P So it's been crazy.
As soon as I do the tests will let you know ;)

**Comment by MrAmericanMike** [comment]
Ok confirmed, the problem was that I was not extending EntityChicken, now I tried a Chicken extending the Vanilla one and it goes into the Pen. Gonna make sure it recognize the drops (Laying items) and all that, but progress :D and confirmation, extending vanilla chicken makes them work.

http://imgur.com/a/9tvSh

**Comment by MrAmericanMike** [comment]
Ok everything working perfectly ;)

http://imgur.com/a/UHZjx

PS: I see that now you have BaseMetals Ores on More Chickens, so I may just use your mod that is way better than what I was doing. But for future reference and for anyone doing custom chickens this thread can help.

Thanks a lot, sorry on the delayed answer ;)

**Comment by GenDeathrow** [comment]
Its is all good, Glad you got it to work though at least for anything else you may need, I'm still updating more mods.
