### ISSUE TITLE
client crash on server after placing down nest and chicken egg on it

### ISSUE THREAD

**Issue by r3b3lxxleader** [GenDeathrow/Hatchery#187]
[crash-2019-02-27_02.30.23-client.txt](https://github.com/GenDeathrow/Hatchery/files/2909246/crash-2019-02-27_02.30.23-client.txt)

I placed down a nest and after I placed an egg in it it started crashing me client side only on a server and even after being able to leave the area if I go back in it it crashes me again

**Comment by GenDeathrow** [comment]
This was already fixed last October. I would recommend updating to the latest version of hatchery. We are on version 2.2.1. your using version 2.1.3. Which had a known issue with rendering with the forge because forge had changed some of its rendering code.
