### ISSUE TITLE
Not much an issue but a question (Maybe an issue)

### ISSUE THREAD

**Issue by MrAmericanMike** [GenDeathrow/Hatchery#19]
Would it be possible to use the Eggs from Hatchery as recipe items on CraftTweaker?

I tried something like...

`var waterChickenEgg = <hatchery:hatcheryegg>.withTag({eggColor: 153, display: {Name: "Water Chicken§r Egg"}, storedEntity: {IsChickenJockey: 0 as byte, HurtByTimestamp: 0, Leashed: 0 as byte, Health: 4.0 as float, Attributes: [{Base: 4.0, Name: "generic.maxHealth"}, {Base: 0.0, Name: "generic.knockbackResistance"}, {Base: 0.25, Name: "generic.movementSpeed"}, {Base: 0.0, Name: "generic.armor"}, {Base: 0.0, Name: "generic.armorToughness"}, {Base: 16.0, Name: "generic.followRange"}], FallFlying: 0 as byte, LeftHanded: 0 as byte, ForcedAge: 0, AbsorptionAmount: 0.0 as float, ArmorDropChances: [0.085 as float, 0.085 as float, 0.085 as float, 0.085 as float], EggLayTime: 6000, Type: 206, InLove: 0, DeathTime: 0 as short, CanPickUpLoot: 0 as byte, HandDropChances: [0.085 as float, 0.085 as float], PersistenceRequired: 0 as byte, id: "chickens.ChickensChicken", HurtTime: 0 as short, Age: -24000}});`

(Had to remove 2 properties for CraftTweaker to take this as a valid value)

But even when on JEI it shows the right chicken egg for the recipe, when actually carfting in game, you can actually use any egg from hatchery and it will work anyway.

Is there a workaround for this?

**Comment by GenDeathrow** [comment]
I have never used crafttweaker so I cant tell ya for sure. Can you not look for a specific  variable  in a  tag?  the two things that say what chicken it is.. is "Type" & "id" But apart from that. I not entirely sure on crafttweaker.

**Comment by MrAmericanMike** [comment]
When you use CraftTweaker, you can do something like "/mt hand" this will give you all the information the mod see about the item you are holding in your hand.

For example, for a Gold Chicken Egg it gives all this:

> <hatchery:hatcheryegg>.withTag({eggColor: 13421568, display: {Name: "Gold Chicken§r Egg"}, storedEntity: {IsChickenJockey: 0 as byte, HurtByTimestamp: 0, Leashed: 0 as byte, Health: 4.0 as float, Attributes: [{Base: 4.0, Name: "generic.maxHealth"}, {Base: 0.0, Name: "generic.knockbackResistance"}, {Base: 0.25, Name: "generic.movementSpeed"}, {Base: 0.0, Name: "generic.armor"}, {Base: 0.0, Name: "generic.armorToughness"}, {Base: 16.0, Name: "generic.followRange"}], FallFlying: 0 as byte, LeftHanded: 0 as byte, ForcedAge: 0, AbsorptionAmount: 0.0 as float, HandItems: [{}, {}], ArmorDropChances: [0.085 as float, 0.085 as float, 0.085 as float, 0.085 as float], EggLayTime: 6000, Type: 300, InLove: 0, DeathTime: 0 as short, ArmorItems: [{}, {}, {}, {}], CanPickUpLoot: 0 as byte, HandDropChances: [0.085 as float, 0.085 as float], PersistenceRequired: 0 as byte, id: "chickens.ChickensChicken", HurtTime: 0 as short, Age: -24000}})

I see Type: 300 and id: "chickens.ChickensChicken"

I will focus on that Type value and see if JEI and CraftTweaker recognize it that way. Thanks on the feedback, I would really love to get this working ;)

**Comment by MrAmericanMike** [comment]
Well, can close this. Apparently it was me doing the things wrong, by the Author of CraftTweaker he made it more clear what I should have been using ;)

`...anyway, ".withTag" is for output items, input items need

.onlyWithTag
`

Still having some problems to make them work, but I leave it here just as a clarification also, for anyone trying something similar ;)

**Comment by GenDeathrow** [comment]
Ok glad you got it fixed out. sorry I wan't more help on that.
