### ISSUE TITLE
What pipes connect to nesting boxes?

### ISSUE THREAD

**Issue by charlesbevans** [GenDeathrow/Hatchery#21]
I've tried EU2's transfer nodes and Embers' item pumps, but neither extracts from the boxes.

**Comment by GenDeathrow** [comment]
I may have forgotten something in the code, so I will look into that. But I do know that Ender IO pipes do work, as all my testing with pipes was with ender IO.

**Comment by GenDeathrow** [comment]
@charlesbevans did that help ya at all? Im currently looking into adding more support though.

**Comment by charlesbevans** [comment]
Sorry, I thought I closed this. I didn't have EIO installed at the time, but I gave up on Chickens after spending two days trying to breed a gold chicken. I'll come back around to Chickens and Hatchery after this pack I'm making, or more likely when Sky Factory 3 gets released.

**Comment by GenDeathrow** [comment]
Yeah sorry about that. I had also tried to fix a game crash with breeding wrong chickens that seem to mess up the breeding mechanic. I have been working on it tonight.

**Comment by GenDeathrow** [comment]
here is an example of what you can do untill I can fix it. http://i.imgur.com/sFT7Igs.png

**Comment by charlesbevans** [comment]
Thanks. The breeding problems were the real dealbreaker. I'll be back when Sky Factory 3 is out. I'm hoping it goes well. I'd like to add an alchemical recipe to create Chicken eggs for my pack and Hatchery is a must.

**Comment by GenDeathrow** [comment]
I don't blame ya, its one of the main features for hatchery, and I really hope too many didn't get too upset about it.  Unfortunately with modding, when you fix one thing you break another. And I test everything before I release, but got past me cause I was trying to make sure vanilla and modded chickens couldn't breed as they cause crashes. Thanks for being patience with me. I love to hear more about what your doing? Also SF3 should be coming within the week.

**Comment by charlesbevans** [comment]
I'm messing with an Embers-inspired dwarven-themed pack based on WTF Expedition and Underworld. In my last game I had been traveling in a Nomadic Tent, and I was going to store some Chickens inside for resources. I was thinking that dwarven alchemists might find the means to create ore-laying chickens. It's a simple recipe add, although I'm also working on the design for an alchemy mod that uses other mods' resources. i.e., I'd use the furnace, brewing stand, etc. for recipes and focus on mod interaction.
