### ISSUE TITLE
[QUESTION] Chickens mod special chickens don't breed

### ISSUE THREAD

**Issue by hron84** [GenDeathrow/Hatchery#24]
I checked both mod's descriptions about how this thing works and I feel myself lost. I have a Log chicken and a Flint chicken from "Chickens" mod, based on JEI they could produce Coal chickens. However, I put both chicken into a nesting pen, faced them each other and they are in neighbouring blocks, but the breeding just don't happen. What do I wrong? I tried to feed them with seeds, but in nesting pen they're not accepting seeds. I'm not impatient, I'm waiting for 3 RT hours to breeding happen, but now I started to think about what did I wrong.

Both mod on latest curse version.

**Comment by GenDeathrow** [comment]
LOL I was just about to make an Issue on this.. I noticed this just now. Which sucks that I pushed a broken mechanic. I was trying to fix an issue with  incomparable chickens. causing a crash. I will try to get an update out later tonight. But Thank yo for bringing this to my attention.  For now breed them outside the nesting pens, until the next update.

**Comment by hron84** [comment]
@GenDeathrow Thanks for the quick reply, I will do it outside then. Do you have plans when you can fix it? I know this is X-mas, so no hurry - just I want to keep my eyes open.

**Comment by GenDeathrow** [comment]
Its fixed in version https://minecraft.curseforge.com/projects/hatchery/files/2357915

**Comment by hron84** [comment]
@GenDeathrow I'll check it out as soon as I can.
