### ISSUE TITLE
[ENHANCEMENT] Add backward recipe for chicken manure block

### ISSUE THREAD

**Issue by hron84** [GenDeathrow/Hatchery#25]
Could you please add the backward recipe to uncraft manure block to 9 manures? If you do this, compacting drawer from StorageDrawers would allow to store it. It would be very nice. As far as I see, manure block has no other effect other than a crafting component of liquid fertilizer, so this step would not be a gamebreaking change.

**Comment by GenDeathrow** [comment]
Welp never thought of this... oops.  I just pushed an update and for some reason this didn't show up before hand.. cause that would have been an easy addition. Look for it in the next update.

**Comment by GenDeathrow** [comment]
Just waiting for curse to approve..

**Comment by hron84** [comment]
@GenDeathrow it's 0.1.15?

**Comment by GenDeathrow** [comment]
0.2. Fuse has been delayed with holidays
