### ISSUE TITLE
Breaks Lava/Water eggs

### ISSUE THREAD

**Issue by Cuppycake** [GenDeathrow/Hatchery#26]
mechanics {
    # Sets if players can throw eggs to hatch chickens. [default: true]
    B:"Can Throw Eggs"=false
}

This config breaks lava and water eggs from the chickens mod. Usually the lava and water eggs can be right clicked on the ground to produce a source block. Right click with this config does nothing. Any way to omit these two eggs from that sort of mechanic? This also breaks Chickens dye eggs as you have to throw them to collect the dye.

**Comment by Cuppycake** [comment]
yeah I literally just saw that in my test world after my edit. Spent all morning balancing chicken drops for my pack and saw it more on accident, forget that part I'm a derp lol. 

Thanks for the help. Can't wait for the next release. love the mod and the amount of config work that can be done.

**Comment by GenDeathrow** [comment]
I got it fixed for my dev enviroment, I have a few more things that willl have to get fixed before I push an update.

**Comment by GenDeathrow** [comment]
Ok I pushed the update.. just waiting for forge to approve it.
