### ISSUE TITLE
Not producing any eggs

### ISSUE THREAD

**Issue by bondgb** [GenDeathrow/Hatchery#3]
Maybe I'm not clear on the functionality, but I've been testing 5 iron chickens in creative and all I've gotten is manure and feathers. What gives?

edit: Nvm, one just dropped, guess it just takes a while ;)

**Comment by GenDeathrow** [comment]
Yeah im looking at upping the drop rate more.. they are a little less often

**Comment by GenDeathrow** [comment]
Its all alpha so tweaking rates will be a big thing. 10% chance atm.  To drop a special egg. 65 to drop a normal egg.  But this version  .  Was more of getting it up and running.

**Comment by bondgb** [comment]
I understand, but it's never too late to think about balance ;) Are you planning on keeping them un-automatable? That's what I'd prefer personally.

**Comment by GenDeathrow** [comment]
They can be somewhat automatable but I will have config options for most things.I love addingin configs.. especially stuff like drop rates. And I love the more realism feel too.
