### ISSUE TITLE
Crashing my world whenever I have more than two hatchery nests touching

### ISSUE THREAD

**Issue by LightningAvenger** [GenDeathrow/Hatchery#30]
As best as I can figure, my worlds crash on startup if I put more than two hatchery nests next to each other. As long as I'm careful to put something else between them and not just have a long line of hatchery nests, the world doesn't seem to crash. Lost three worlds to it before I finally figured it out. Temporary solution: Don't be dumb, just keep them in pairs lul.
Crashlog: http://paste.atlauncher.com/view/75c498e5

**Comment by GenDeathrow** [comment]
What version are you on? and crash happens with the "Pen's" from what I see.

**Comment by LightningAvenger** [comment]
Ah, I see. I'm still on 0.1.11 and didn't see the update. Well, thanks for pointing that out for me...
