### ISSUE TITLE
Nest Server Crash - Sponge related

### ISSUE THREAD

**Issue by Cuppycake** [GenDeathrow/Hatchery#31]
It appears that when something happens in the nest the server will crash. I imagine part of the mutation process or something. Taking eggs in and out do not cause it. Doesn't seem to always happen.

http://pastebin.com/eiVXpNJm

**Comment by GenDeathrow** [comment]
I'm going to add a catch in., hopefully that will stop this issue, but cant make promises.

**Comment by GenDeathrow** [comment]
This should be fixed with latest update.  if not I will reopen

**Comment by Cuppycake** [comment]
I'll have people put theirs nests back out lol.  Thank you.

**Comment by GenDeathrow** [comment]
sorry for the issues it created
