### ISSUE TITLE
EnderIO Overflow Tank (no idea)

### ISSUE THREAD

**Issue by coder444** [GenDeathrow/Hatchery#32]
I right clicked a Lava Egg on an EnderIO Tank and it...
overflowed.
Hatchery: Latest (On Curse)
EnderIO: Latest (On Curse)
Ender Core: Latest (On Curse)

If you don't know what I mean, here's a screenshot.
![2016-12-29_10 39 23](https://cloud.githubusercontent.com/assets/14946719/21552019/7cc46f7c-cdb3-11e6-990f-17b4f5268812.png)

**Comment by GenDeathrow** [comment]
Fist question. Is it a hatchery egg or the lava egg drop by the lava chicken. Screen shot the egg if your not sure.

**Comment by coder444** [comment]
Ah. Chickens has the problem...

**Comment by coder444** [comment]
lava chicken

**Comment by GenDeathrow** [comment]
Its all cool our mods are closely tied together.. he gets my issues sometimes.
