### ISSUE TITLE
Harvestcraft Support

### ISSUE THREAD

**Issue by mallrat208** [GenDeathrow/Hatchery#33]
Tested with Hatchery 0.2.1

It would be nice if you could register the Hatchery Egg to the OreDictionary under "listAllegg" as well as "egg".

The Hatchery eggs are tagged for the OreDictionary as 'egg' which catches a few mods by default. What it doesn't catch however is Harvestcraft since all the recipes that use or would use a regular egg instead refer to 'listAllegg'

**Comment by GenDeathrow** [comment]
This will be added in soon with a big update I am working on.

**Comment by forteddyt** [comment]
Have you got an eta on this? I'm also looking for a similar feature.

**Comment by GenDeathrow** [comment]
its all cool
