### ISSUE TITLE
Inserting eggs into nests via hoppers/pipes not fully functional

### ISSUE THREAD

**Issue by zwof03** [GenDeathrow/Hatchery#35]
Eggs can be inserted into Hatchery Nests using hoppers or pipes, but the egg does not render (does not "appear" in the nest) or hatch. 
Waila tooltip denotes that the Nest/Egg status is "Hatching: 0.0%" and does not progress.
Tested with vanilla, Hatchery, Chickens and More Chickens eggs.
Tested with vanilla Hoppers and EnderIO Item Conduits.
Using a clean install of 1.10.2 Forge 12.18.3.2202 with only Hatchery, Chickens, More Chickens, EnderIO, JEI and Waila.

**Comment by GenDeathrow** [comment]
Actually it was never suppose to be able to be inserted. Im suprised it even sortof works. 

I never added the proper mechanics for eggs to be inserted. And be cause of that I never tried. The only realy way is to use a block that is a fake player like EU2 mechanical user. Its very strange it worked... I dont think they have an inventory slot.

**Comment by zwof03** [comment]
Well that explains it. I only discovered it by accident as well.
Although being able to pipe/hopper into the nests is an interesting mechanic that might be worth exploring further.
However, not with the basic nests as that might be a bit unbalanced.
Perhaps an "Incubator" block that requires a redstone lamp, egg nest and nesting pen to craft, and allows eggs to be inserted and requires a redstone signal to operate.
This way the resource cost is in line with the functionality and adds some progression to the hatching process as well as allowing some automation without reliance on external mods.
So I guess consider this a feature suggestion.

**Comment by GenDeathrow** [comment]
oh your talking about the chicken nesting pens, yes you can pip into them, I just forgot to put a stopper on those, but I have come up with some really neat vanilla systems to use less hoppers by making staircases of the nesting pens.

Even though Im using proper terminology for nest and nesting pen, I feel I need to change that. Nesting pens are just for collection items from chickens, and nest are for just hatching eggs.

**Comment by zwof03** [comment]
Nope. I'm referring to the Egg Nest. :)

**Comment by GenDeathrow** [comment]
alright I see whats happening, so I will see about fixing it, looks like I may just implement piping in. will see. I haven't completely decided yet.

**Comment by zwof03** [comment]
Awesome. If you do block inserting into egg nests,  please consider my incubator suggestion as an advanced egg hatching mechanism.

**Comment by GenDeathrow** [comment]
Incubator was already a planned feature.. I have to get certain items in places before thand though.

**Comment by zwof03** [comment]
Sounds great!

**Comment by GenDeathrow** [comment]
ok so next version hoppers can no longer interact, had too many issues trying to get them too.

**Comment by GenDeathrow** [comment]
Should be fixed with beta version "0.2.3"
