### ISSUE TITLE
[Sky Factory 3 v3.0.4 - Hatchery v0.22] Chicken stats gone from waila tooltip.

### ISSUE THREAD

**Issue by Boomflex** [GenDeathrow/Hatchery#37]
As above.

Updated to latest SF3 v3.0.4 and the chicken stats are no longer in the waila tooltip.

https://gyazo.com/d485fc5a5080ea3163f30b3eddb5dddf

**Comment by Boomflex** [comment]
Apparantly "Chickens" added a Chicken Analyzer which only shows in Waila once you've "analyzed" them...

This change by them directly interrupts the working of Hatchery. Is this intended?

**Comment by GenDeathrow** [comment]
I guess I'm confused on how it interrupts hatchery?  Hatchery still works with the stats. Eggs show the stats when the chickens lay eggs. Only thing I couldn't get them to work with is Chicken nesting pens. For what ever reason I couldn't show their stats.

**Comment by GenDeathrow** [comment]
Also chickens is adding in configs to turn that function off as well so you always see stats. Im sure thats a settng that will considered to be turned off in SF3. As long is I make sure darkosto knows about it.
