### ISSUE TITLE
Hatchey not sending Property Direction to client

### ISSUE THREAD

**Issue by tyler489** [GenDeathrow/Hatchery#38]
http://pastebin.com/wDhmzqqy

Playing Skyfactory 3 on a SPONGE/forge server

Crashes clients anytime they get close

**Comment by GenDeathrow** [comment]
I will double check the things I have in place for this, but me and a lot of devs are getting issues with Sponge servers, and Sponge has 94 open issues with mods. conflicts. I not entirely sure what is going on with it.  But I will double check my my stuff just in case.

**Comment by tyler489** [comment]
im Aware of the issues with sponge but i thought i would report it anyway

**Comment by GenDeathrow** [comment]
I appreciate it, I may still have an issue with this, I might have messed up the logic on this particular block. I haven't had issues with my other blocks. Im working on a new update for hatchery this week. So I will do some crazy testing

**Comment by GenDeathrow** [comment]
Should be fixed in 0.2.4

**Comment by GenDeathrow** [comment]
Closing for now
