### ISSUE TITLE
Egg Duping with Hoppers

### ISSUE THREAD

**Issue by Slackaholicus** [GenDeathrow/Hatchery#39]
Issue Description:
Eggs can be duped when the hatchery nest is placed above hoppers

Steps to reproduce:
1. Place hopper
2. Place hatchery nest above hopper
3. Place egg into nest

Note:
Noticed when playing on Sky Factory 3, tested in SMP with just forge and the necessary mods, easily reproduced the bug.

**Comment by GenDeathrow** [comment]
Well thanks for reporting,  Inventory support wasn't suppose to happen with this at all. I am looking into another issue dealing with that.

**Comment by GenDeathrow** [comment]
ok, fixed it Hoppers can no longer interact with it.  I tried allowing hoppers to interact, but too many issues with that.

**Comment by GenDeathrow** [comment]
Should be fixed with Beta version "0.2.3"

**Comment by GenDeathrow** [comment]
0.2.4 Since 0.2.3 was messed up
