### ISSUE TITLE
JEI breeding integration not working

### ISSUE THREAD

**Issue by bondgb** [GenDeathrow/Hatchery#40]
Hi. I'm playing SkyFactory 3 and updated Hatchery (and More Chickens) to check out the new roosters, but I found the JEI breeding plugin not working. I'm guessing this is because of Hatchery's latest update, since it was working OK a day ago.

Anyway, this is what the log says: http://pastebin.com/qLFi1chP

Using JEI 3.14.2.401

**Comment by GenDeathrow** [comment]
Rooster isnt breedable he spawn into he world. I dont have his informatin up on the wiki yet. You will need a large platform.

**Comment by bondgb** [comment]
I understand, but I mean the JEI info on crossbreeding is missing, for every chicken breed.

**Comment by GenDeathrow** [comment]
Oh.. crap I will look into it.. I just realized what you meant. Strange didnt show on my side.

**Comment by GenDeathrow** [comment]
Did you update "chickens" mod? And does hovering over the nesting pen in jei and pressing "u" give you any jei infromatuon?  I swear I had tested with newest chickens mod and it worked.

**Comment by GenDeathrow** [comment]
Ok this is a derp on my side with "more chickens".. untill I can work around it. Downgrade to the last version( delete your old morechickens.cfg). Or give chickenosto and funwaychick parents in the config file.

**Comment by bondgb** [comment]
I don't know if this was related, but also when I updated and came into my world my 10/10/10 chickens were gone from their nesting pens as well.

**Comment by GenDeathrow** [comment]
@bondgb https://github.com/GenDeathrow/Hatchery/issues/42. Here is the issue. Im working on it.

**Comment by GenDeathrow** [comment]
Fixed on Chickens Mod side
