### ISSUE TITLE
Eggs breakable in dispenser

### ISSUE THREAD

**Issue by Homarus** [GenDeathrow/Hatchery#41]
Is it possible to make eggs breakable when you fire it with a dispenser? If you like the idea, setycz did it in the ChickensMod 4.3 update, maybe you can check his code.

**Comment by GenDeathrow** [comment]
Gll ready added 0.2.3 version. Make sure yo can see beta builds

**Comment by Homarus** [comment]
The update to 0.2.3 removed all of my chickens in the nesting pens. The chickens that where in the nesting pens are from Chickensmod. 

Details: Modpack Skyfactory 3.0.4
+ ChickensMod updated to 4.3
+ Hatchery updated to 0.2.3

Tested also in an empty world (MC 1.10.2), same result.
Details: forge: 12.18.3.2202
ChickensMod 4.3
Hatchery 0.2.3
MoreChickens 1.0.9

**Comment by GenDeathrow** [comment]
Is your config settng set true to be able to throw eggs?

**Comment by Homarus** [comment]
To throw the eggs works fine in the new update. Only after updating the mod it removed all of my chickens that are in a nesting pen. And yes, Can throw eggs=true

**Comment by GenDeathrow** [comment]
sorry I was at work and I couldn't see the message where you sad the dispenser works.  Im looking into the nesting pen issue.

**Comment by GenDeathrow** [comment]
Welp.. that's a problem..

**Comment by GenDeathrow** [comment]
https://github.com/GenDeathrow/Hatchery/issues/42
