### ISSUE TITLE
Items not persistant

### ISSUE THREAD

**Issue by Mezeral** [GenDeathrow/Hatchery#47]
All nesting pen items are cleared upon server restart and or crash. This is happening consistently on the server I play on. Not sure what else to add to it, other than it's on the Skyfactory 3 pack if that helps with the working environment.  

Ex:
- before restart
Chicken
next drop ~ 1 min
Slot 0: Egg
Slot 1: Feather
Slot 2: Chicken Manure 
- after restart
Chicken
next drop ~ 1 min

**Comment by GenDeathrow** [comment]
What version are you guys on for Hatchery?

**Comment by GenDeathrow** [comment]
I think you on an old version where this was fixed already. But kinda need you to confirm whats on the server.

**Comment by lilmoefow** [comment]
The version of Hatchery on our server is hatchery-1.10.2-0.2.2.jar

**Comment by GenDeathrow** [comment]
well your about 5 updates behind, I had a couple of fixes since than, most I can tell ya is update and see if the bug still exist.
