### ISSUE TITLE
Actually Additions worms and fertilized soil

### ISSUE THREAD

**Issue by bubblesayoyo** [GenDeathrow/Hatchery#49]
Pretty self explanatory, the worm doesn't see the block as usable. 

Opened an issue up at AA as well, however they said they don't want to do any special cases, just wondering if there is anything you guys can do on your end. He said "It checks if the block instanceof BlockDirt or instanceof BlockFarmland." Not sure if that can be done or not. Thanks!

**Comment by GenDeathrow** [comment]
I get it I wouldnt do special cases either.  There was a reason why I didnt do the instance of dirt and farmland. Although I cant remember. I think dirt had something to do with the types ot has. I take another look at it and see what the worms are doing.

**Comment by bubblesayoyo** [comment]
Sounds good, Thanks!

**Comment by GenDeathrow** [comment]
Going to close this for now, I got ender io to fix the farming station to work , but dont thin AA is going to add support for this.
