### ISSUE TITLE
Automatic egg placing into hatchery nest

### ISSUE THREAD

**Issue by KnexxFan** [GenDeathrow/Hatchery#50]
Is there a way the eggs can be placed into the hatchery nest with a machine?
I am currently playing SkyFactory 3 and I seem to be unable to find a machine that is able to do this.
My plan was to fully automate the chicken making with the chickens mod but if there is no block that is able to place the eggs into the hatching nest I will not be able to do this.

**Comment by GenDeathrow** [comment]
EU2 mechanical user will place. And I believe EU2 has a block that checks a block state and can send a pulse to the mechanical user.
