### ISSUE TITLE
losing Drops nesting pen (Hatchery v0.2.7 (1.10.2) [Fix])(when close the game)

### ISSUE THREAD

**Issue by Lightone** [GenDeathrow/Hatchery#54]
when you save and close the game or open other save, the drops of nesting pen disappear.

**Comment by GenDeathrow** [comment]
Well not sure why its doing it.. but I just confirmed it. I had to rewrite some of the code handling this stuff last couple updates must have broken something. Either way for now I have pipes/ or a hopper underneath to collect the items so they don't completely get lost.

**Comment by GenDeathrow** [comment]
got it figured out
