### ISSUE TITLE
placing down nests causing server problems

### ISSUE THREAD

**Issue by jackytuutykcaj** [GenDeathrow/Hatchery#56]
When ever I place down, interact or break a hatchery nest, the server hangs a bit and causes players to be kicked with a fatal error. It then kicks players out again after they relog unless the server restarts.

**Comment by Kashdeya** [comment]
what version of the mod are you using? any logs? what modpack? all the info you can add to this will help way more.

**Comment by GenDeathrow** [comment]
the Crash logs would be nice too. Nothing has changed in the nest code in a long time. I bet it has something to do with what ever the waila replacement changed.

**Comment by jackytuutykcaj** [comment]
Modpack is skyfactory3 v3.0.6.

**Comment by GenDeathrow** [comment]
I really need a crash log. I have nothing to go on. It would be like looking at a needle in a haystack. logs from the server are nice, and logs from client that kicked...

**Comment by GenDeathrow** [comment]
I have a feeling this is just related to this.. https://github.com/GenDeathrow/Hatchery/issues/53
