### ISSUE TITLE
Just an idea for eggs

### ISSUE THREAD

**Issue by MrAmericanMike** [GenDeathrow/Hatchery#57]
Would it be possible to have a config option, to make chickens on pens only lay their eggs when they are next to another pen with chickens on it and disable the egg when they are alone with no pen to the sides, or with empty pens.

I think that would make much cleaner farms.

**Comment by GenDeathrow** [comment]
Technically there is a config already. Im at work atm cant remember what it is. But is currently set to 50% so in theroy setting it to 0 should work or 0.01

**Comment by MrAmericanMike** [comment]
Ohhh ok, I'm a dingus, I didn't even check the configs LUL :P Thanks for the headsup, I will look into that.

**Comment by MrAmericanMike** [comment]
Perfect, that did the trick. Thanks a lot.
