### ISSUE TITLE
Time per tick increase indefinitly

### ISSUE THREAD

**Issue by krakaen** [GenDeathrow/Hatchery#58]
I was playing Sky Factory 3 version 3.0.6 & 3.0.5 (hatchery v 0.2.5) and i noticed something weird.

When i place chickens from the chicken mod in the pens, in time, the time/tick will augment with no limit

ex :  I had 56 chickens in pens, the time/tick was  1.6 when i placed them. 10 hours later, that time/tick was 12.3.
We had the issue that at some point, that time/tick was at 260 on the server, just from those pens.

I installed TickProfiler and made some test, that exemple was with the hatchery pens.

I also try with no pens at all and the time/tick stayed at 1.6 for 12 hours straight.

I do not know if it is a problem from your mod, but when you use the pens, over time, it will cause an issue

**Comment by GenDeathrow** [comment]
If you can export the informationnon the tickprofiler id like to see or screenshot. Also is server counsole outputtng? 

There is an interaction issue with a hwyla. That seems to be causing alot of issues. I wonder if this is at all connected.

**Comment by krakaen** [comment]
I just looked and it doesn't give any logs that contain the tickProfiler...

I can tell you how to recreate it, but I don't have the setup for 260 anymore...

to recreate, just place pens(like 100) with chickens inside, do a profile e
then wait 1-2 hours and redo another one, it would normally show me a higher time/tick than at the start

**Comment by GenDeathrow** [comment]
This one is going to be hard to pin point.. I will leave this. But so far your the only one to report this issue. I am waiting from some others to get back with me to see if they notice this also.

**Comment by GenDeathrow** [comment]
@krakaen I know this is a bit late, but RL got crazy around here. But I think I tracked this issue down and is in the latest beta builds.

**Comment by GenDeathrow** [comment]
hoping this got fixed with some performance increases
