### ISSUE TITLE
Nest and Pen replacement block models

### ISSUE THREAD

**Issue by charlie-e09ae35d** [GenDeathrow/Hatchery#6]
I made an attempt at more "vanilla" block models for Nest and Pen. If you like, please use them without any restrictions and modify or suggest modifications to be made.
[Preview](http://i.imgur.com/VgLwwAD.png), [Download](https://db.tt/rA3DfBIq)

**Comment by GenDeathrow** [comment]
I appreciate it, but I personally like the higher res textures.. but if anything.. if you turn that into a resource pack.. than I could give a link for ppl who will want the more vanilla like textures..

**Comment by charlie-e09ae35d** [comment]
I might do that when you will implement a few more things, thanks.

**Comment by GenDeathrow** [comment]
Cool. I got a couple side projects I am working on for a pack developer.. but I will get some new updates in the next week or so.

**Comment by GenDeathrow** [comment]
More I think about it.. I may use this. Will see.
