### ISSUE TITLE
Nest and Nesting Pen Textures

### ISSUE THREAD

**Issue by Exsolutus** [GenDeathrow/Hatchery#63]
I was wondering if you have plans to change the textures for the Nest and the bed of the Nesting Pen. Speaking honestly, they are rather over-resolution. The Nest is especially difficult to look at up close because of this.

**Comment by GenDeathrow** [comment]
Your right its been on my to-do list for a while. I'm not big fan of the vanilla textures for that though. But just so texture packs work by default I may change it. It not game breaking which is the only reason why it hasn't changed

**Comment by Mrbysco** [comment]
When me and my girlfriend came by this mod while playing Sky Factory 3 we couldn't look at the stuff as it looked out of place. I made a temp fix for me and my girlfriend.
![Alternate Texture Fix](http://i.imgur.com/8ETXyPn.png)

[Imgur Album](http://imgur.com/a/p9mDJ)

(In my private fix I fixed the UV mapping on the nesting pen as it stretched the textures)


-Mrbysco

**Comment by GenDeathrow** [comment]
@Mrbysco if you send me the json's, I may use parts of it, As Im' not sure when I will sit down to fix these my self. I wont use of all the textures you did, but I may use some and tweak them.

**Comment by Mrbysco** [comment]
@GenDeathrow Here you go. Do with it whatever you want 😃  https://www.dropbox.com/s/zy2py1vj7xsxr4v/Hatchery%20Patch.zip?dl=0 
I only did what I did because the 32x textures looked out of place to me.

-Mrbysco

**Comment by GenDeathrow** [comment]
done
