### ISSUE TITLE
The One Probe Integration

### ISSUE THREAD

**Issue by ivardensphere** [GenDeathrow/Hatchery#65]
I recently moved to The One Probe from Waila in 1.10.2 and was hoping there may be a chance that you would consider integrating the same information from Waila into The One Probe.

https://mods.curse.com/mc-mods/minecraft/245211-the-one-probe for reference.

**Comment by GenDeathrow** [comment]
It wouldn't be a bad idea to add it in.. I check out their api

**Comment by ivardensphere** [comment]
Awesome! IF you need any testing or input let me know.

**Comment by GenDeathrow** [comment]
will do.. api looks simple enough. I get back to ya when I get it.. for now I have an update that needs to go out. so it wont be on the next update.

**Comment by ivardensphere** [comment]
Never a rush! I appreciate the mod and you taking the time looking into it.

**Comment by BrisingrAerowing** [comment]
I second this, as I use TOP now, and I like it a lot better than WAILA. I don't mod, so I don't know what is needed. I will gladly test as well.

**Comment by GenDeathrow** [comment]
I'm currently working on a big update. I was planning on it.

**Comment by GenDeathrow** [comment]
Ok hopefully next version will have The One Probe support. I just started adding it.

**Comment by GenDeathrow** [comment]
https://github.com/GenDeathrow/Hatchery/commit/ba35d11bbb2205aeaa1c7dde5b69c2d3b7e8bc5f#diff-a3534d9ecd324f1d0ead7587b1093886

**Comment by GenDeathrow** [comment]
I had to put this on hold cause of some bugs.. the code is there, but I had to turn it off atm.
it will be worked on soon though

**Comment by GenDeathrow** [comment]
should be back in latest beta build
