### ISSUE TITLE
Suggestion: Config option to restrict net usage

### ISSUE THREAD

**Issue by chaosblad3** [GenDeathrow/Hatchery#66]
Just my opinion but I think there should be an "chickens only" option in the config so that the Animal net can only be used on types of chickens and not other passive mobs, as in most modpacks there are other (usually more expensive) alternatives (golden lasso, wand of capturing etc), that modpack devs could then force people to use instead.

With the config option set to true the net could be renamed in-game to "Chicken Net" instead of "Animal Net" for the sake of clarity.

**Comment by IamAlathe** [comment]
I support the idea of this being a config option.  If you're playing an easy/fun pack, you can leave in on all animals, if the pack is supposed to be more challenging, it doesn't make sense to be able to put a cow in your pocket with early game materials. :)
