### ISSUE TITLE
Suggestion: Feathers -> Wool

### ISSUE THREAD

**Issue by chaosblad3** [GenDeathrow/Hatchery#68]
Just a simple recipe you could add as an extra use for the masses of feathers that people end up with ;)
![image](https://cloud.githubusercontent.com/assets/4968222/22853649/4637d9b2-f054-11e6-990d-d10a465f7d9c.png)
Shears should take 1 durability damage per use and remain in the crafting table.

**Comment by GenDeathrow** [comment]
I do have plans for feathers but I appreciate suggestions though.

**Comment by Exsolutus** [comment]
Honestly... not a terrible idea. Although, turning feathers into wool doesn't make a lot of sense. Maybe add a "Down" block that's oredict'd with wool? *shrug*

**Comment by GenDeathrow** [comment]
just for a reference, this is the what I will be basing the feathers on. http://thepoultryguide.com/uses-of-chicken-feathers/

**Comment by JoshHawley** [comment]
SWEET! According to that link, you are implementing diapers in minecraft!!! =p

**Comment by Syndaryl** [comment]
Golf balls used to be made with feathers, too, they were called "Featheries" (duh). The feathers were rendered down by boiling (smells absolutely vile) and packed into leather cases. The rendered feathers are a springy collagen filling for the balls; they're actually pretty good for golf, but take way too much effort to make to be affordable (sewing the little cases is a PITA, stuffing them with feather goop is a bigger PITA).
Which means stuffing things that need to be hard but a bit springy is another possible use. 

Now I'm imagining throwing feathery balls at creepers.

**Comment by GenDeathrow** [comment]
I actually kinda like that idea, Ive been a little slow on getting the next update. Oher things have take away from modding.

**Comment by GenDeathrow** [comment]
well.. its only been forever.. but this has been implemented.. slightly different mechanic. Feathers In Shredder -> fibers to fiber pads -> fiber pads to wool. More recipes will be added as time goes on.
