### ISSUE TITLE
Nesting Pen Breeding

### ISSUE THREAD

**Issue by Quarris** [GenDeathrow/Hatchery#69]
So I have been messing with the Chickens mod as well as More Chickens and Hatchery. When I went ahead and bred some chickens in hatchery. If the chickens were both 10/10/10 then the offspring would also be 10/10/10. I didn't see a config options for this so if it there let me know, but it might be nice to have a options to disable the stats of the parents to go down to the offspring. At least not all of it as this seems to be quite easy to get high stats quite easily, so something like 2 10/10/10 chickens would breed a 3/3/3 or something.

**Comment by GenDeathrow** [comment]
I get what ya mean, but hatchery actually has nothing to do with the stats that are given.  That's all handled by Chickens Mod.  In fact he is switching how the breeding works, but his updates have slow down some this last month and half.
