### ISSUE TITLE
Textures overlying others render issue with Hatchery block

### ISSUE THREAD

**Issue by charlie-e09ae35d** [GenDeathrow/Hatchery#7]
Only occures with Hatchery model, changing block model to hand made one does not fix it.
[Screenshot_1](http://i.imgur.com/13dGCFj.png), [Screenshot_2](http://i.imgur.com/QEF2Z2D.png), [Screenshot_3](http://i.imgur.com/b6GwkZo.png), [Screenshot_4](http://i.imgur.com/dImPblU.png)

**Comment by GenDeathrow** [comment]
Its a known issue with the nesting pen. This is my first attempt at the json modeling. So I'm not entirely sure whats going on with it.

**Comment by charlie-e09ae35d** [comment]
Got it, unfortunately I cannot help you with this. Feel free to close this issue if you don't need it in the tracker.

**Comment by GenDeathrow** [comment]
Fixed v.0.1.1
