### ISSUE TITLE
No longer seeing egg or chicken infromation in WAILA when hovering over nest and nesting pen

### ISSUE THREAD

**Issue by chyne** [GenDeathrow/Hatchery#70]
I just updated to the latest version and I am no longer seeing the WAILA info when hovering over nests and nesting pens (no egg type, no hatch percentage, etc).

**Comment by GenDeathrow** [comment]
Update your HWYLA. https://github.com/GenDeathrow/Hatchery/issues/53

**Comment by chyne** [comment]
I don't have HWYLA (running a custom pack). Do I need it for the latest version of Hatchery?

**Comment by GenDeathrow** [comment]
Yeah HWYLA is a continuation of WAILA.  So from her on out HWYLA is the better choice.
