### ISSUE TITLE
Baby chickens spew feathers in presence of nesting pens

### ISSUE THREAD

**Issue by niftybottle** [GenDeathrow/Hatchery#71]
I'm running into a bug on my server where baby chickens spew gobs of feathers out like a firehose if they hatch near a nesting pen. It occurs regardless of whether the nesting pen is occupied, but doesn't happen if the nesting pen isn't placed in the world. It stops when I kill the baby or it turns into an adult. It occurs on Hatchery versions 0.2.7 and 0.2.10, running with Chickens mod 4.3.2 and More Chickens 1.0.11. A list of all mods running is [available here](https://www.technicpack.net/modpack/the-new-nifty.954910/mods). I have not yet tried placing the nests far away or running it singleplayer.

**Comment by GenDeathrow** [comment]
So the baby isn't in the nesting pen and is dropping feathers?. Nesting pens drop feather based off a timer only when occupied, not the chicken. And nesting pens do not have any kinda of area effect. The only area effect is feeders and they will speed up chicken growth and slightly speed up drop speed. but that speed is tiny. Ill look into it. But does any other mod you know give feather drops?

**Comment by niftybottle** [comment]
oh boy, a lot make feathers drop. Quark and Botania off the top of my head, but I don't know that they'd do anything with the chickens from the Chickens mod. It's not a subtle effect, my inventory would completely fill with stacks of feathers, within a matter of seconds, and it's pretty binary - baby chickens hatched when there is a nesting pen placed in the world spew feathers, ones hatched when the nesting pens are in my inventory shed feathers at a normal rate.

**Comment by niftybottle** [comment]
I'll try disabling the botania/quark shedding and see if it's a weird mod interaction - it's not like I don't have a terrifying amount of feathers anyway.

**Comment by niftybottle** [comment]
Actually, are chickens not supposed to drop manure/feathers outside of the nesting pen? Because mine drop both, even wild chickens do.

**Comment by GenDeathrow** [comment]
Only manure I don't drop anything else. Feather drops aren't me. Feathers do get dropped inside nesting pens. And thats me plus any other mod that drops feathers.

**Comment by niftybottle** [comment]
Ok, this appears to be an incompatibility between the Chickens mod and Quark. I was misled by the fact that it doesn't affect tier 1 chickens, and the later tiers are when I started using your mod to breed. Apologies for wasting your time.

**Comment by GenDeathrow** [comment]
Dont worry about that. You actually reported it right. We discussed it, and it lead ya closer to the issue. This is how user and dev should work. I was out this weekend ,so I could not actually do testing. I appreciate it. So no you did not waste my time. Thank you
