### ISSUE TITLE
enderio farm machine compatibility

### ISSUE THREAD

**Issue by Tenchu98** [GenDeathrow/Hatchery#72]
The fertilized dirt can't be tilled with the enderio farmer and a tinkers mattock. I tried an obsidian how too, not from tinkers, and still no luck.

**Comment by GenDeathrow** [comment]
Its know its because enderio looks specifically for minecraft dirt. it doesnt work with modded dirt like mine that can be tilled.. and wont work.  Nothing I can realky do on my end at this point.
