### ISSUE TITLE
Server crash: Description: Ticking block entity

### ISSUE THREAD

**Issue by Gunner76th** [GenDeathrow/Hatchery#73]
[crash-2017-03-13_05.06.24-server.txt](https://github.com/GenDeathrow/Hatchery/files/838813/crash-2017-03-13_05.06.24-server.txt)
I just woke up and was informed that our Sky Factory 3 server had crashed (but had shut down gracefully) during the early morning hours. To that extent I do not have details other than what is in this crash report as to the reason of the crash.

**Comment by GenDeathrow** [comment]
What version of Skyfactory 3 are you running?

**Comment by GenDeathrow** [comment]
That is a very strange crash, I actually have null pointer catches before that part of the code is called. It may have been the server mishap. Tell me if this continues to happen. Your not using Sponge are you for your server? It didn't look like it from the crash log, but I have to ask.

**Comment by Gunner76th** [comment]
Oh god no. No sponge, no cauldron, no bukkit, just pure forge. We are running the latest release of forge, which I think is 2254. 

This is the first time the server has ever crashed like this, and from the crash report, I thought it was that 2 chickens that were in pens were trying to mate in a way that was not allowed or something lol

**Comment by GenDeathrow** [comment]
Love that response.. well your right its during the mating code. Problem is to reach that part of the code a chicken has to be present. Which means that it loses the chicken after its already check fora chicken. It shouldn't happen. Thats kinda why I think the server hiccuped. But if it continues it needs a fix for sure. I may add a secondary null check just in casen

**Comment by Gunner76th** [comment]
And we are running the most recent release of Sky Factory, but we also manually updated all the mods to the most recent release versions as of last week IIRC.

**Comment by GenDeathrow** [comment]
well just keep me informed if it keeps happening. I have a lot of mods needing worked on. so its in a queue, unless it becomes a major issue. Thanks for reporting it.

**Comment by Gunner76th** [comment]
[crash-2017-03-14_05.31.18-server.txt](https://github.com/GenDeathrow/Hatchery/files/841338/crash-2017-03-14_05.31.18-server.txt)
Seems we had another crash about 3 hours ago. I am restarting our server, and plan to go to the location of the pen to get a screen shot to see if that helps you any.

**Comment by Gunner76th** [comment]
![2017-03-14_08 57 39](https://cloud.githubusercontent.com/assets/5566872/23901639/8abe3da8-0894-11e7-87a8-ad38906845ed.png)
![2017-03-14_08 57 49](https://cloud.githubusercontent.com/assets/5566872/23901640/8af48c14-0894-11e7-941d-9554109afb3f.png)
![2017-03-14_08 57 56](https://cloud.githubusercontent.com/assets/5566872/23901641/8b2bba0e-0894-11e7-91a6-249163706952.png)
![2017-03-14_08 58 37](https://cloud.githubusercontent.com/assets/5566872/23901642/8b3d2f00-0894-11e7-86b0-aa4da6ac98f5.png)

**Comment by Gunner76th** [comment]
We are testing to see if it is those 2 front chickens under the apple, or what it is. I have the owner moving the 2 iron chickens to a new location, but keeping them beside each other. If it crashes again we should know if it is isolated to the iron chickens, or if it is a bug in general with the nesting pens.

**Comment by Gunner76th** [comment]
So it has been 9 days since I had the player move the 2 chickens that kept crashing us, and we have not had any further issues. It would appear that there was some freak event happening with those 2 specific chickens when they were placed near all the other chickens.

**Comment by GenDeathrow** [comment]
I had another server report this too.. and it hasn't happen again.. its very strange.. but I will have an update soon that will hopefully catch it next time anyways

**Comment by GenDeathrow** [comment]
https://github.com/GenDeathrow/Hatchery/commit/d227a54f518c4e3698ac61007b211aefe34b2b54

Catching a null pointer now just in case.. will be in the next update. may still be a bit but its here
