### ISSUE TITLE
Why Do roosters lay eggs?

### ISSUE THREAD

**Issue by tyler489** [GenDeathrow/Hatchery#76]
Seriously... Roosters are Guys... they shouldnt lay eggs...

**Comment by GenDeathrow** [comment]
Ive already got a fix for it.  Its because they extend off chickens in vanilla. 

Next update will have it.

**Comment by tyler489** [comment]
;) Config option for Geneticly correct chickens?

**Comment by GenDeathrow** [comment]
https://github.com/GenDeathrow/Hatchery/commit/d227a54f518c4e3698ac61007b211aefe34b2b54

**Comment by GenDeathrow** [comment]
Should be fixed in latest beta build
