### ISSUE TITLE
Random server crashes

### ISSUE THREAD

**Issue by Mrtenz** [GenDeathrow/Hatchery#77]
My Foolcraft server crashes at random times, with a NullPointerException in the crash report, related to Hatchery.

Here is the crash report: https://hastebin.com/ihibifoyur.hs

**Comment by GenDeathrow** [comment]
I believe I have already fixed this issue in my dev environment, but I'm in the middle of a major update, so I don't know when I can push a new build.

**Comment by GenDeathrow** [comment]
this should be fixed in the latest beta build
