### ISSUE TITLE
Add Mekansim?

### ISSUE THREAD

**Issue by supertommyhd** [GenDeathrow/Hatchery#79]
I love to play Sky Factory III, but I feel like it's missing something.  Then, I realized: It was missing Mekanism.  Mekanism is a fantastic tech mod that adds awesome things, such as the MOST powerful generator in the whole game, early game flight, a whole plastic manufacturing system, flamethrowers, teleportation blocks, and an energy storage bank that can store up to about 700 TerraRF.  Please consider adding this mod!

**Comment by GenDeathrow** [comment]
I very confused by what happening here right now. I'm the Hatchery mod dev?  SF3 is an FTB mod pack. You are in the wrong place for reporting or requesting anything SF3 related.

**Comment by Turkey2349** [comment]
I love playing Skyrim, but I feel like it's missing something. Then, I realized: it was missing Unicorns. Unicorns are amazing animals that would add awesome things, such as the MOST styling transportation in the whole game, great diversity, a whole lot of swag, rainbows, sparkles and a way to get around the map traveling at a whopping 1 horsepower. Please consider adding this animal.

Relevance? Abolutley none. Next time post in the appropriate place.

**Comment by supertommyhd** [comment]
Sorry, I clicked the wrong place when I was trying to find the Sky factory
3 github project
