### ISSUE TITLE
(Suggestion) Allow empty nets to be stackable

### ISSUE THREAD

**Issue by Ravalli03** [GenDeathrow/Hatchery#80]
I love this mod and the nets are great to use catching mobs. I think it would be great for empty nets to be stackable to at least 16. When out exploring, and finding chickens, moo cows etc, it takes up the limited space me have to carry them.

**Comment by ktole1999** [comment]
can you place captured nets in a bag or backpack? what about ender chest/pouch

**Comment by GenDeathrow** [comment]
yeah I can see about that, will depend on how I have it setup though.

**Comment by Ravalli03** [comment]
@ktole1999, that's what I'm doing now, it's not just when using them, it's also storing them in a inventory. Also those who use this mod without mods that have backpacks, rs, etc

@gendeathrow, thanks for looking into it!

**Comment by GenDeathrow** [comment]
Will be in next update 

https://github.com/GenDeathrow/Hatchery/commit/255233031d1542a6ad461f09e14e4a82d8b82f7d
