### ISSUE TITLE
crossbreading dont work on SPongeforge

### ISSUE THREAD

**Issue by tyler489** [GenDeathrow/Hatchery#81]
I cant seem to breed them outside the nesting pins they wont take seeds.
in addition chickens dont seem to drop specialty drops in nesting pins https://github.com/SpongePowered/SpongeForge/issues/1259

**Comment by GenDeathrow** [comment]
Wrong mod Hatchery and Chickens are two separate mods by different devs. But the Chickens mod dev has been MIA for a little while now.

**Comment by GenDeathrow** [comment]
And really you should report this to spongeforge

**Comment by tyler489** [comment]
it was reported

**Comment by GenDeathrow** [comment]
Ok but if you read your first comment you said. 

"I cant seem to breed them outside the nesting pins they wont take seeds." << Chickens.. 

I already know about the SpongeForge issue. Its a sponge forge issue.
