### ISSUE TITLE
(Suggestion) Add blockstates for pen

### ISSUE THREAD

**Issue by kikipunk** [GenDeathrow/Hatchery#87]
Hello

Since one of last update, the pen doesn't change his state (pen -> pen_chicken).
If is not bug, I suggest adding the blockstates "chicken" (true/false) like the nest.

I used this block update to change model:
http://imgur.com/wCorhR1

Thanks

**Comment by GenDeathrow** [comment]
I removed the block states because they caused other issues, and they weren't really needed anymore. Question how did you use the state to change the model? you could just change the model via texture pack.

**Comment by kikipunk** [comment]
When I was talking about blockstates, It's like the egg nest (http://i.imgur.com/GNvor9q.png)

**Comment by GenDeathrow** [comment]
right, I was tried last night.. tell ya what I will add a  block state into it. it may take an update or two though.

**Comment by GenDeathrow** [comment]
your models are great by the way, modeling isn't my thing, I be linking your stuff to my page.

**Comment by GenDeathrow** [comment]
I didn't add this in the latest version, but it will be in the next as long as no major issues come from it.

**Comment by GenDeathrow** [comment]
https://github.com/GenDeathrow/Hatchery/commit/8b65762f438dc42d53b1d3929207ded760558005

**Comment by GenDeathrow** [comment]
getting close to update this.. closing this issue for now
