### ISSUE TITLE
Internal Inventory for nests - *Please*

### ISSUE THREAD

**Issue by ktole1999** [GenDeathrow/Hatchery#92]
Awesome mod, nice work. Is there a way to implement an internal inventory that once full the nest will stop functioning. What i am seeing on my server is items are spewing on ground when normal item path/chest is full. this quickly escalates to massive entities. Any thought or suggestions?

**Comment by GenDeathrow** [comment]
Is this a spongeforge server or forge? cause I don't actually call items spawning outside the nesting pen unless the pen is actually broken. I know that spongeforge has issues with spawning items outside the nesting pens.

**Comment by ktole1999** [comment]
Yes this is sponge server and I have seen issues posted about item drops on sponge.

Question. When nesting pen generates drops and there is no inventory connected where do drops go. Is there an internal inventory?

We are using 1.10.2-0.3.11



Sent via the Samsung Galaxy S® 6, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by GenDeathrow** [comment]
if the inventory is full.. than it doesn't do anything. its gets cleared.

**Comment by GenDeathrow** [comment]
![image](https://cloud.githubusercontent.com/assets/3720710/26771928/e024830e-4987-11e7-8b6e-db858a12dfd4.png)

**Comment by GenDeathrow** [comment]
This sounds like a sponge issue with the way they handle items.

**Comment by ktole1999** [comment]
gotcha, will monitor sponge post. thanks
