### ISSUE TITLE
Chickens swapping or disappearing

### ISSUE THREAD

**Issue by thegreatersea** [GenDeathrow/Hatchery#93]
On updating the mod, I logged in to a server to find that the nest that previously contained my constantan chicken was completely empty. That chicken was found sitting on a nest containing uranium chicken drops. My uranium chicken was found sitting on a nest containing aluminum chicken drops. My aluminum chicken was gone entirely. Trying to hatch one of my aluminum eggs produced a uranium chicken. Breeding or hatching new eggs produced the correct chickens with no further issues. Another user reported that throwing a constantan chicken egg crashed the client, but produced no server crashlogs.

**Comment by GenDeathrow** [comment]
I need more information.  like the actual version number of the mod, What type of server are you running, forge or spongeforge?
Preferably the crash log the other user was getting.

**Comment by Vaygrim** [comment]
https://minecraft.curseforge.com/projects/coop-life
"Coop Life" Pack version 1.5.1 for Minecraft 1.10.2
Hatchery-1.10.2-03.17
Chickens-4.3.1
MoreChickens-1.10.2-1.1.4
Forge 2316

If you want a full mod pack install to test on, you can grab "Coop Life" off the Twitch / Curse Launcher and install the latest update for it. (v1.5.1)

**Comment by Vaygrim** [comment]
Crashlogs relating to this ARE incoming as well, should be posted here shortly.

**Comment by GenDeathrow** [comment]
Wait your using 'Chickens 4.3.1" you should be on the latest, that version had broken code?

**Comment by Vaygrim** [comment]
Chickens 4.3.2 , sorry. That was a typo on my part.
"chickens-4.3.2.jar       6/15/2017 1:22 PM     223KB     Executable Jar File"

**Comment by GenDeathrow** [comment]
https://github.com/GenDeathrow/Hatchery/issues/98

Im not closing this issue, per say, Im just moving it over to issue 98.
