### ISSUE TITLE
Chickens mod: Chickens loose AI when pulled from Nesting Pens

### ISSUE THREAD

**Issue by asherons** [GenDeathrow/Hatchery#95]
Playing Sky Factory 3, version 3.0.13
Which has Chickens version 4.3.2 and Hatchery 3.17

After removing some chickens from Nesting Pens with an Animal Net the chickens loose their AI.  They don't move anymore, but they do still make their drops. They can be bred, they get the heart effect, but then nothing happens, no babies are born.

Some chickens can be taken from Nesting Pens without issue.

Placing the chickens back in the Nesting Pens and then removing them does not fix the issue.

It happens on at least 5 types of chickens I've tried. Emerald/Glowstone/Ender/Diamond/Redstone.

No other mods were added to the pack and none were removed.

The issue is repeatable.

**Comment by GenDeathrow** [comment]
is this a new world or old world?

**Comment by asherons** [comment]
This is an absolute great mod, thanks for making it.

I just checked, the world was originally made 3.0.10 and recently updated to 3.0.13.

Issue seems to have occurred after upgrade.

**Comment by GenDeathrow** [comment]
I'm wondering if this has to do with the jump in hatchery versions.

**Comment by asherons** [comment]
Just wanted to share the issue in case it meant something to you.

As a work around a person can put a non-AI chicken in a Nesting Pen and wait for new eggs to drop, then hatch those into normal chickens.

**Comment by ArkitektBMW** [comment]
Writing in to say I've had this in a completely new world in the new version.  Only thing I added (to Sky Factory 3) was MalisisDoors.  I started this world with Optifine, without issue, then pulled it and started the world without it; then re-added it.

When I started with the log and bone chickens, I pulled them from the nesting pens (after 10-10-10ing) and they had AI.  This just cropped up for me after I've got about 12 nesting pens full of chickens.

One other thing, vanilla chickens come out without AI as well.  I tried pulling them out with nets, and also breaking the nesting pens themselves, both spit out AI-less chickens.

**Comment by GenDeathrow** [comment]
yeah I realized the breaking pen I forgot to re-enable the AI, also Im not sure why its happening when your using a net. its not suppose to do that. I'll be gone this week end. so dont be surprised if you dont hear from em.

**Comment by macks2008** [comment]
Oh good, this is fixed. I had also been having this one but hadn't been able to narrow down the cause. Thanks for patching it ^-^

**Comment by GenDeathrow** [comment]
I may need another patch but it works most times.. and breaks sometimes. Most of this was a pull request from a contributor and I didn't catch the issues before it got released. and not I have to try and make time to track it down.
