### ISSUE TITLE
[Bug] [IE]Chickens ID's got shifted, Server crash right after start

### ISSUE THREAD

**Issue by ZXQWAS** [GenDeathrow/Hatchery#98]
After updating SkyFactory from 3.0.12 to 3.0.13, I couldn't launch the server anymore. It loads everything and right in the end always crashes with this log: https://pastebin.com/eizQkjpS
Not sure if it's exactly Hatchery, but Hatchery was updated from hatchery-1.10.2-0.3.15 to hatchery-1.10.2-0.3.17. Downgrading doesn't seem to help though.

**Comment by GenDeathrow** [comment]
I haven't narrowed this down completely, It could be that a certain chicken was removed between those versions, It seems to be more of a pack issue than the mod it self, I am adding in a check to not crash the game out when it happens though. its actually the chicken it self inside the pen that's crashing.

**Comment by ZXQWAS** [comment]
I've actually made it run by downgrading MoreChickens from 1.10.2-1.1.4  to 1.10.2-1.1.3, leaving Hatchery at 0.3.17. There's a Constantan chicken in that pen.

**Comment by GenDeathrow** [comment]
Welp, I just figured out what happened chicken id's got shifted because I had moved a chicken out of IE addon to the base materials, basically aluminum chickens turned into uranium chickens, and constantan  chickens dont exist, This is why the new versions of chickens will not contain int ids. But you helped me figure this out.

**Comment by GenDeathrow** [comment]
basically if you want to fix it, you'd have to remove all constantan chickens, uranium, and aluminum chickens, and replace them after updating. I apologize for the inconvenience, I don't think I have an easy fix for this, cause new worlds will be fine, old worlds are broke, If I change it again, new worlds will break old worlds will be fine. But with the new system we are working on, this should never happen again.

**Comment by GenDeathrow** [comment]
The newest version of More chickens adds a new chicken to fill in the missing id's so your server/world will start up again. but Immersive engineering chickens will have shifted id's
