### ISSUE TITLE
Chicken Feeder overstuffed with seeds

### ISSUE THREAD

**Issue by uberfuzzy** [GenDeathrow/Hatchery#99]
![screenshot 2017-07-01 21 19 06](https://user-images.githubusercontent.com/1438723/27766596-62aaecf2-5ea3-11e7-996a-9ec7a344e91b.png)

Hatchery 0.3.17
MC  1.10.2

I have a barrel of seeds connected to the feeder by way an EnderIO conduit.

**Comment by GenDeathrow** [comment]
Strange, I'll have to see whats causing that.

**Comment by GenDeathrow** [comment]
yea very strange, Im looking at my code if it happens to be over 200 it automatically sets it to 200. So I have no idea how it happened.  unless it was a visual glitch with HWYLA

**Comment by GenDeathrow** [comment]
cant seem to get this to recreate it.. closing for now
